### ISSUE TITLE
sync webdav URL error "Unable to open this folder. Please make sure it exists"

### ISSUE THREAD

**Issue by pixelseventy2** [owncloud/ios#770] opened 2016-09-10 15:22 UTC
### Steps to reproduce
1. Log in to owncloud server on iOS
2. Open folder
3. Get the message "Unable to open this folder. Please make sure it exists"
### Expected behaviour

Folder should open and be browseable
### Actual behaviour

You get the message "Unable to open this folder. Please make sure it exists"
### Server configuration

**Web server:**
CentOS 7, Owncloud is running under the folder /owncloud/.  Errors still occur if using a rewrite rule to direct /\* to /owncloud/*

**Database:**
MySQL, on separate server.
**PHP version:**
5.4.16
### Client

**iOS version:**
9.3.4 - Client is set to use a server address including the /owncloud/

**ownCloud app version:**
3.5.0

**Device model:**
Ipad Pro 9.7
#### Web server error log

Without redirect:
192.168.0.185 - - [10/Sep/2016:16:14:12 +0100] "GET /owncloud/status.php HTTP/1.1" 200 96
192.168.0.185 - - [10/Sep/2016:16:14:13 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 404 216
192.168.0.185 - - [10/Sep/2016:16:14:18 +0100] "PROPFIND /remote.php/webdav/p/webdav/Passwords/ HTTP/1.1" 404 235
192.168.0.185 - - [10/Sep/2016:16:14:21 +0100] "PROPFIND /remote.php/webdav/p/webdav/Personal/ HTTP/1.1" 404 234

With redirect:
192.168.0.185 - - [10/Sep/2016:16:14:52 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 302 246
192.168.0.185 - chris [10/Sep/2016:16:14:52 +0100] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 12168
192.168.0.185 - chris [10/Sep/2016:16:14:53 +0100] "GET /owncloud/ocs/v1.php/apps/files_sharing/api/v1/shares?path=&subfiles=true HTTP/1.1" 200 1083
192.168.0.185 - - [10/Sep/2016:16:15:14 +0100] "PROPFIND /remote.php/webdav/p/webdav/Passwords/ HTTP/1.1" 302 265
192.168.0.185 - chris [10/Sep/2016:16:15:14 +0100] "PROPFIND /owncloud/remote.php/webdav/p/webdav/Passwords/ HTTP/1.1" 404 246
#### ownCloud log (data/owncloud.log)

No logs generated

 
### Tell us what could be improved:

the iOS app is attempting to connect, assuming that OC is running in the root, regardless of what the server URL is set to.  It also corrupts the URL when connecting; see the extra "/p/webdav" in the webdav URLs above.  This does not happen if owncloud is running in the root.

**Comment by nasli** [comment] 2016-09-12 13:45
Hi @pixelseventy2, 
thanks for your feedback, will check it.

**Comment by guruz** [comment] 2016-09-14 15:46
Which exact URL did you set in the client settings?

**Comment by pixelseventy2** [comment] 2016-09-19 07:42
I tried:
https://owncloud.p*****.net/owncloud
https://owncloud.p*****.net/owncloud/

and after setting up the redirect from / to /owncloud/ tried:
https://owncloud.p*****.net
https://owncloud.p*****.net/

The latter worked fine after I moved OC from /owncloud/ to / - This setup with the /owncloud/ has been working on Android for years and still is, and was working on iOS until very recently

**Comment by nasli** [comment] 2016-09-19 10:33
@pixelseventy2 thanks for your feedback will check it

**Comment by denisblum** [comment] 2016-10-20 05:50
I have the same problem. See separate issue.
From my point of view, its a problem from the iPhone App Owncloud Version 3.5.1 and not from the owncloud-server settings, because i dont receive the error message by using iPad or Safari by desktop.

Do you have a solution?

**Comment by denisblum** [comment] 2016-10-21 09:00
Do you have any news for us / me? 
Is the problem / error reproducible ?

**Comment by denisblum** [comment] 2016-10-27 06:26
Hi Nasli,
What about the issue?
Do you have good news for us?
Is an update for the iphone app available?

Please note: the app on iPad works fine! Its only the iphone Version

Please give me a feedback

**Comment by jesmrec** [comment] 2016-11-03 08:45
@pixelseventy2 could you provide us an test account? we can not reproduce the error.

**Comment by endcarnage** [comment] 2016-11-19 10:07
@jesmrec: A friend of mine has the same error on my installation, so I could provide you with a test account. How should I send you the access data?

**Comment by jesmrec** [comment] 2016-11-19 11:14
@endcarnage send it to apps@owncloud.com. Thank you!!!!

**Comment by jesmrec** [comment] 2016-11-21 09:09
Checking the server you sent, i could not reproduce the error. I browsed correctly through different folders i created in the account with any error.  

I used an iPhone with v9.3.5. 

Is the problem reproducible yet?

**Comment by denisblum** [comment] 2016-11-21 09:14
I still have the Problem with iphone 10.1.1
It seem that it works with iphone < 10????

Or?

**Comment by jesmrec** [comment] 2016-11-21 10:11
@denisblum 

Checking with iOS 10.1.1, i can reproduce the bug, so it seems to be a problem related with that iOS version. I checked it with iOS 9.3 like the reference in first message.

Please do not close the test account, if it is posible.

@nasli, i use the following set-up to reproduce:

iPhone 6 Plus
iOS v10.1.1 (14B100)
app versions 3.5.x

with iOS version 9.3.x -> not reproducible

**Comment by jesmrec** [comment] 2016-11-23 12:58
today i performed a check with the test account and the 10.1.1 device, but the problem is now not reproducible with the same environment as the latest try.

@denisblum could you check with this (or another) account if the problem persists?

**Comment by denisblum** [comment] 2016-11-23 16:56
I still have the problem !
What can we do?

**Comment by denisblum** [comment] 2016-11-23 16:58
My device:
Iphone 6 plus
10.1.1
App 3.5.1

Still not working

**Comment by jesmrec** [comment] 2016-11-23 17:29
is the problem reproducible in the same account you sent?

**Comment by endcarnage** [comment] 2016-11-23 21:11
The error occurred in another account. We just tested it here and it only occurred in the other account. We compared both accounts and I noticed as a difference, that one account had a capital first letter firstname and lastname. So we changed that in the test account and the error was reproducible there. We wanted to make sure it was really the cause, so we changed back to the older full name and the error was gone. Sadly after changing again to capital letter firstname/lastname the error did not occurr again.

So I wanted to let you login into the account where the error occurs, so we moved all files from that account and changed the password, so we can let you access it, but after that the error was gone. And of course whatever we do, now the error does not occur again.

So the problem seems to be not reproducible with my server anymore and I have no clue, what could possibly cause it.

**Comment by denisblum** [comment] 2016-11-24 06:49
I dont know, if oi undestand you right. I cant change existing usernames!?? But its right, all accounts have a capital first letter firstname and lastname. by using a new Test user with Username "tester", i still receive the problem!
From my point of view, we do not have a problem with usernames, because everybody are able to login. The error came by choosing / open a folder. Another point is, that the app runs perfect by using iphone 5 with <v10 and with iPad or other devices.

Perhaps the following point will help you to fin the problem:
it seems that users with iPhone >v10 are able to login but the folder structure are old! the structure will not refresh. by choosing a folder or by manualy refresh the folder view the error is coming.

**Comment by denisblum** [comment] 2016-11-24 07:00
Another point:
everything is fine, if i use the cloud by using safari on every device !
it seems thats the problem is the app

**Comment by jesmrec** [comment] 2016-11-24 08:43
did you upgrade the version from a later one? or installed it from apple store?

**Comment by endcarnage** [comment] 2016-11-24 19:40
@denisblum  I did not change the username, but on the webinterface at least the Adminstrator has the option to specify real names of the user. Changing that real name on the server did shortly cause that error, but not reproducible.

Also deleting all files of the affected user on the server using the webinterface, did remove the error for that user.

@jesmrec I have forwarded that question to my frined. I myself don't have an apple device and the error occurred on the device of my friend. He has installed the app from the appstore and says that he did not install any updates, but I did update the version of owncloud on the server.

**Comment by jesmrec** [comment] 2016-11-29 10:31
@endcarnage any feedback from your friend?

**Comment by endcarnage** [comment] 2016-11-30 17:43
> He has installed the app from the appstore and says that he did not install any updates, but I did update the version of owncloud on the server.

That was his feedback.

**Comment by nasli** [comment] 2016-11-30 18:10
@endcarnage have you tried to remove user account inside the app and added it again? This can be performance on the app settings view

> but I did update the version of owncloud on the server.

Which was the update in the server that you did? 
upgrade server version? In that case from witch version.
change endpoint on the server? Maybe more subpaths?
added some kind of redirection?

**Comment by davivel** [comment] 2016-12-01 09:54
@endcarnage , @denisblum , please, provide logs from the server; take them right after reproducing the bug in the iOS app.

@pixelseventy2 , is this still an issue for you?

Thanks

**Comment by endcarnage** [comment] 2016-12-01 19:13
@daviel The error ist not reproducible anymore for me, but the error should be in this part of the archived logs: http://pastebin.com/LVrdXj7N (access.log and error.log)
The important webserver settings are:
DocumentRoot /var/www/kraven.my-wan
Alias /owncloud "/var/www/owncloud/"

@nasli I think the information from my friend was wrong, sorry for that. I just searched through my messenger archive and can reconstruct the following chain of events:
- He reported the app isn't working anymore (i presume after installing an update of the app)
- I tried to figure out, what was wrong and found out I did not have the latest version of owncloud installed, because owncloud moved to another repository and I had it installed from the old one
- I assumed the error in the app was caused by an incompatibility between newest app and old owncloud-server-software
- I updated the server from version 8.1 to 9.1 (currently 9.1.2 is installed using the ) and to the new repository http://download.owncloud.org/download/repositories/stable/Debian_8.0/
- The app did still not work
- I tried to give you access to the account with the error and the error was somehow solved

**Comment by pixelseventy2** [comment] 2016-12-01 19:38
It's not been an issue for me for a while, as I was able to change my instance to run at the root of the site, not under the /owncloud folder

**Comment by kuking** [comment] 2016-12-08 16:47
Hi, I think I have the same error:

- I can see the list of files and folders as soon as I open the app i.e. "Folder1, Folder2, me.jpg"
-  tapping on the image `me.jpg`, I get the following error message:
> It is not possible to connect to the server at this time.

- The following appears in the `access.log`:

`[...] "GET /cloud/index.php/apps/files/api/v1/thumbnail/64/64/ebdav/me.jpg HTTP/1.1" 404 29 "-" "Mozilla/5.0 (iOS) ownCloud-iOS/3.5.1"`

- tapping on a folder "Documents", I get the following error message:
> Folder could not be created.

- The following appears in the `access.log`:
`[...] "PROPFIND /remote.php/webdav/ebdav/Documents/ HTTP/1.1" 405 166 "-" "Mozilla/5.0 (iOS) ownCloud-iOS/3.5.1"

**Please notice the suspicious "ebdav/" in the URLs, It feels like a string manipulation gone wrong**; Finally: My ownCloud is installed in a `/cloud` path prefix. Which has exactly the same amount of characters (6) as `ebdav/`. Suspicious enough for me.  --Thanks!

**Comment by ggdiez** [comment] 2016-12-21 13:44
Hi @kuking 

I agree with you perhaps something is going wrong in the method that create the url dynamically. I need to check it in the debug mode with your server. 
 
Can you provide us a test user of your server?  Send it to apps@owncloud.com

Thanks,

**Comment by jesmrec** [comment] 2017-02-20 09:24
@pixelseventy2 @denisblum @endcarnage @kuking 

could you check if the latest release 3.5.3 fix the problem?

**Comment by kuking** [comment] 2017-02-20 14:02
I'm sorry but it is not fixed in 3.5.3. I'm still getting the error "Folder could not be created".
(but it has always worked on my ipad, only the iphone fails.)

**Comment by jesmrec** [comment] 2017-02-20 14:05
ok @kuking i tried with the test account you sent us and seems not to work. We should keep on researching on that issue and the test account would help us.

**Comment by kuking** [comment] 2017-02-20 14:07
I'm sorry but I haven't provided a test account (maybe somebody else?), I would like to do it but it can't be done in the organisation i'm dealing with. Sorry. :(

**Comment by jesmrec** [comment] 2017-02-20 14:09
i have a test account and i though you sent it. I have review the whole thread and i noticed that @endcarnage did it.

**Comment by davivel** [comment] 2017-03-15 08:50
@kuking, what URL did you enter in your account? Did you include the ```/cloud``` path in it?

Is it feasible for you to delete the account in the device and create it again? If your server is redirected in some way, there is a chance that the URL was wrongly stored in a previous version and that the error persists even after upgrading to 3.5.3.

**Comment by kuking** [comment] 2017-04-03 10:58
@davivel hi, tried by re-creating the account and it works now! Thanks!
Apologies for the delay in answering, I was not available.

**Comment by nasli** [comment] 2017-04-05 13:46
Thanks for the update @kuking !!

@denisblum, is it still an issue for you? In that case, please reopen it, thanks!!

**Closed by nasli** 2017-04-05 13:46 UTC
Labels: Bug, Needs info, sev2-high
