### ISSUE TITLE
Implement support for Touch ID

### ISSUE THREAD

**Issue by martva** [owncloud/ios#517] opened 2015-11-12 11:51 UTC
I would love to see that I can use Touch ID on my Iphone for logging into the ios app.

**Comment by javiergonzper** [comment] 2015-11-12 11:54
We want to use the TouchId as the PinCode to go to the app if it is closed... it is on our backlog :+1:

**Comment by nasli** [comment] 2015-11-19 16:31
Duplicate of #124

**Closed by nasli** 2015-11-19 16:31 UTC
