### ISSUE TITLE
instant upload feature for pictures taken on the phone.

### ISSUE THREAD

**Issue by rjimenezsg** [owncloud/ios#13] opened 2012-11-21 12:23 UTC
Add this feature to ownCloud client

**Comment by nasli** [comment] 2015-01-05 08:22
Happy new Year!!

This feature is currrently in progress. It will be included in iOS app in upcoming versions.

**Comment by RobbieBott** [comment] 2015-01-05 08:24
Sweet. Thanks for the update.

**Comment by rodgal23** [comment] 2015-02-05 14:02
Date for the new version of the app?

**Comment by javiergonzper** [comment] 2015-02-05 17:39
We hope release the next version on the end of February or at the beggining of March :+1:

**Comment by rodgal23** [comment] 2015-02-05 17:42
Thanks!!!

**Comment by jeffmcneill** [comment] 2015-02-15 05:27
+1

**Comment by rodgal23** [comment] 2015-02-20 15:31
YES! the new version of the APP is out

**Comment by scho0ck** [comment] 2015-02-20 15:46
But the feature is not available yet ?!

**Comment by rodgal23** [comment] 2015-02-20 15:47
The feature is available in the new version?

**Comment by scho0ck** [comment] 2015-02-20 15:49
Have done the update just now and can't find it ?! In fact I cannot see any changes rather than the version number ?

**Comment by enoch85** [comment] 2015-02-20 18:43
@javiergonzper Regarding automativ upload:

> Have done the update just now and can't find it ?! In fact I cannot see any changes rather than the version number ?

> The feature is available in the new version?

**Comment by brandonwagner** [comment] 2015-02-22 15:31
The release notes for the new version just say that the version is to prepare for owncloud 8. I assume it will be in the "What's New" section when the app is released and contains auto-upload, and that they will update this issue.

**Comment by rperezb** [comment] 2015-02-23 18:17
Thanks for your comments.

This feature will be included within the version 3.4.0, under regression test right now.

**Comment by rodgal23** [comment] 2015-02-24 20:49
Date for the version 3.4.0

**Comment by stp-ip** [comment] 2015-03-02 12:30
Will this feature upload all previously made pictures or make this possible at least? Or will it only be uploading new images? How is it going to differenciate, if fotos were already uploaded? Is this info kept on the device?

**Comment by javiergonzper** [comment] 2015-03-02 13:06
Once the user activate the "Instant Upload" we take the identifier of the last photo on the "Camera Roll" and we will upload all the new photos.

**Comment by javiergonzper** [comment] 2015-03-02 13:08
@rodgal23 we hope upload the version this week and it should be approved by apple in 8 days so... could be released at the en of the next week (13th march).

**Comment by stp-ip** [comment] 2015-03-02 13:38
@javiergonzper ok so old fotos won't be possible to be uploaded? So I still have to go through 9k images manually for them to be uploaded as only new images will get uploaded. Any way there can be a upload all fotos option on the first run or something? Or is it already possible to select all files in a folder for upload now aka the whole camera roll directory?

**Comment by enoch85** [comment] 2015-03-11 21:12
@javiergonzper Status update?

**Comment by rperezb** [comment] 2015-03-16 09:50
Thanks for your interest.

@stp-ip yes, instant uploads will only work for new photos. 

The new version is pending Apple approval.

**Comment by stp-ip** [comment] 2015-03-16 20:13
@rperezb Any chance for a feature, which enables the older ones to be uploaded too? As mentioned without selecting each one of the fotos individually?

**Comment by superfunnl** [comment] 2015-03-20 15:46
I just installed the newest version on the iPhone and noticed location services is required for Instant Upload. Why?

**Comment by enoch85** [comment] 2015-03-20 15:58
@superfunnl Probably to locate where the photo was taken. This is used later as information about the photo, and only saved on your device.

**Comment by przybylski** [comment] 2015-03-20 17:46
@superfunnl @enoch85 
Using location is related with how instant upload is implemented.
Because on iOS you cannot directly receive notification when user did take a photo then you need to do it with some trickery.
It works as follows. When user is taking photo iOS saves those taken photo on something called camera roll.
Owncloud holds timestamp of last location refresh (I am not sure how this is initially set @javiergonzper  will know).
When location refresh notification is sent to owncloud application then last camera roll is browsed in search for photos with timestamp younger than last location refresh timestamp. All found photos are put on upload queue and last location refresh timestamp is updated.

AFAIK this is the best way of implementing that.

**Comment by scho0ck** [comment] 2015-03-20 19:17
I must be missing something can't get it to work it only uploads picture if I force close the app and reopen it have already reinstalled the app.

Also interesting would be the limitation about this : does it work on 3G or WIFI only? Also do I understand right that it should work in background so I don't need to open the app just let it run in background??
Thanks

**Comment by bill340** [comment] 2015-03-21 03:44
Automatic-Upload is not working at all.
It just does not upload any new photos.

**Comment by otbe** [comment] 2015-03-21 09:07
Same here. Only works after shutdown and reopening.

The way how the app recognizes new pictures feels broken by design. The permanent GPS/location arrow in the upper right corner makes me feel sad :/

**Comment by TheReal1604** [comment] 2015-03-21 09:20
@otbe Its not only the bad feeling.. the battery is drained, too. What did you think? We need some options for upload only on WiFi connection or something...

**Comment by superfunnl** [comment] 2015-03-21 09:29
@przybylski Thanks for explaining :-)

**Comment by przybylski** [comment] 2015-03-21 09:37
@otbe @TheReal1604 forcing GPS all the time is a bug IMO.
Application should use most accurate location service available (whithout forcing it).
Those services are (from strongest to weakest): GPS, WiFi, Mobile network.
@otbe I understand your doubts about how feature is implemented. Unfortunately Apple doesn't provide any notification when photo was taken (or added to camera roll).

There are two ways to implement this feature.
1) Add filesystem observer which will be invoking upload when filesystem is modified.
2) Use Photos Framework introduced in iOS8

Downside to approach 1 is that application will need to be running for feature to work.
Downside to approach 2 is that you need to maintain two features systems. But it seems to be better than location based upload.

**Comment by otbe** [comment] 2015-03-21 09:37
@TheReal1604 Yes indeed. As a former dropbox user Im missing some configuration params for InstantUpload, too.

After disabling InstantUpload the GPS/location arrow is still there. Only removing ownCloud from my devices "fix it" properly.

**Comment by TheReal1604** [comment] 2015-03-21 09:40
@otbe you can disable location services under privacy.. @przybylski Thanks for explaining.

**Comment by otbe** [comment] 2015-03-21 09:55
@TheReal1604, @przybylski Thanks.

**Comment by mathielen** [comment] 2015-03-21 17:24
+1

**Comment by stp-ip** [comment] 2015-03-21 20:00
I have the owncloud app crashing after enabling InstantUpload (iOS 7.1.2 with an iPhone 4). Any issues known?

**Comment by przybylski** [comment] 2015-03-22 08:10
@otbe I was thinking about this for a while, dig through documentation and came to conclusion that Photo Framework solution suffers the same problem what filesystem observing does.
Application must be running in order to get notification from photo album which limits the usage scenario.
Apple allows background tasks to execute one of this task type:

* Audio and AirPlay
* Location updates
* Voice over IP
* Newsstand downloads
* External accessory communication
* Uses Bluetooth LE accessories
* Acts as a Bluetooth LE accessory
* Remote notifications

There are two scenarios which are suitable for this feature, its Location updates and remote notifications.
Remote notifications are bad choice becuase they require work to be done on server and server doesn't know when device is taking photo. So this would require to invoke remote notification periodically which uses both bandwith and cpu cycles.
Location updates are better way to go because it's local event which doesn't use server unless needed.
It's possible that Apple is using some private APIs for theirs applications which uploads photos to iCloud.
Using such API is possible for ownCloud I guess, but using those makes app be rejected from the AppStore.

**BUT** this doesn't explain the fact that this feature is badly written.

**Comment by bill340** [comment] 2015-03-22 15:36
One question... How does the dropbox instant upload work?
Also, why is instant upload only working, when killing the app and restart it?

**Comment by enoch85** [comment] 2015-03-22 17:29
@przybylski It seems that you have some skills in coding. Why don't you help out improving this feature? :) Just tested, and yes - it works bad. Not directly "out of the box" as you would expect.

**Comment by scho0ck** [comment] 2015-03-22 18:37
So everybody is complaining but apart from that is there any way to get this feature actually working with the latest released version ?

**Comment by enoch85** [comment] 2015-03-22 19:14
@scho0ck Restart your device, and it works after that.

**Comment by otbe** [comment] 2015-03-22 19:26
@enoch85 did not work for me. Photos are only recognized If I kill and restart the app.

**Comment by bill340** [comment] 2015-03-23 08:43
+1

**Comment by przybylski** [comment] 2015-03-23 08:50
@enoch85 why not. i just need to handle some personal stuff. im on freenode IRC under handle aqu if anyone needs me

**Comment by nasli** [comment] 2015-03-23 08:52
The instant upload feature works this way:
Once instant upload are enabled, will check for new photos and upload them when:
1.The user open the app (After kill the app)
2.A signicant change in location was detected

The reason to implement it this way is because we support iOS7 too.

We do not use active gps, instead, we use the significant-change location service. This service delivers updates only when there has been a significant change in the device’s location. This way we do not  have to worry about the battery drain.

The location icon that remains active in the top indicates that the location service is allowed. If we disable the instant upload feature, that icon will disappear in the range of 15 seconds if no other app is using it.

@bill340 Dropbox and others like Mega works the same way.
@stp-ip could you give us more details about your crash? you can open another isuee for it. Thks

This is a first version of this feature, and as always, we apreciate all your suggestion to continue improving the feature. 

For new versions of this feature will be included new configurable options from the setting view like only allow uploads if wifi is active.

Thanks you all for the comments.

**Comment by bill340** [comment] 2015-03-23 08:58
Thanks very much for the infos! 
So I will test, if it uploads, once the location changes. Some explanation in the app would be useful.
Also an option to upload only on wifi or also on 3G/4G would be great.

**Comment by enoch85** [comment] 2015-03-23 11:09
@przybylski Please join #owncloud on IRC. To join the dev team please speak to @karlitschek

**Comment by przybylski** [comment] 2015-03-23 11:10
@enoch85 I know how to contribute ;) I started owncloud for android ;)

**Comment by enoch85** [comment] 2015-03-23 12:29
@przybylski Well then, I'm looking forward to your improvments. ;)

**Comment by javiergonzper** [comment] 2015-03-23 13:12
I found a problem on the Instant Uploads.
It does not work in background if you have the iOS Pin Code or the Touch ID. it happens because iOS encrypt all the sandbox of any app if the device is blocked after 3 minutes. We can set the ownCloud sandbox to not be encrypted but once it is fixed we got the next problem:

       Mar 23 13:14:55 iphone-6-2 Owncloud iOs Client[390] <Warning>: Core Data: error: -executeRequest: encountered exception = error during SQL execution : authorization denied with userInfo = {
	    NSFilePath = "/var/mobile/Media/PhotoData/Photos.sqlite";
	    NSSQLiteErrorDomain = 23;
	}

So it is not possible fix it. If the Pincode/Touch ID is activated the Instant Uploads in Background will not work because Apple do not allow us to access to the Photo gallery :disappointed:

**Comment by rodgal23** [comment] 2015-03-23 20:23
owncloud app crashing after enabling InstantUpload with an iPhone 4 the app is frozen

**Comment by enoch85** [comment] 2015-03-23 20:30
@javiergonzper Can we all agree on that this issue is getting to big? I mean, open a new one for each issue instead. Common sense. :)

**Comment by rodgal23** [comment] 2015-03-23 20:34
Date for the update 3.4.1

**Comment by bill340** [comment] 2015-03-24 00:05
That explaines, why my instant upload does not work, although I changed my location.

**Comment by javiergonzper** [comment] 2015-03-24 09:47
@enoch85 yes, probably we can close this issue and open others to have a better track of the issues
@rodgal23 we are working on it right now, probably we can send the new version to the Appstore this week and then the time that Apple needs to review the app (http://appreviewtimes.com/)

**Comment by enoch85** [comment] 2015-03-24 10:08
Closing this now. Please open new issue reports if you encounter bugs. Did not find any issue template @javiergonzper (maybe you should make one?) But use something like this before you post your issue to get help quicker. https://raw.githubusercontent.com/owncloud/core/master/issue_template.md Thank you in advance.

**Closed by enoch85** 2015-03-24 10:08 UTC
Labels: Enhancement, uploads
