### ISSUE TITLE
Can't download files

### ISSUE THREAD

**Issue by miglosh** [owncloud/ios#351] opened 2015-04-20 10:05 UTC
On my iPad mini 2 with iOS 8.2, I can't access the files in my ownCloud.

Calendar and contacts work just fine.
I can also access the files from my Android phone, from OSX and Windows 8, no problems there.

But in the iOS app, the screen reads "Preparing download" and nothing happens - see screenshot.
![image](https://cloud.githubusercontent.com/assets/9477837/7228018/8e15fe76-e755-11e4-9dd1-463f1ab9084a.jpg)

Only if I deinstall the app and reinstall it and then try to access the files, it works just fine.

**Comment by javiergonzper** [comment] 2015-04-20 10:55
Hi @miglosh 

Looks like you problem is the same than this other issue https://github.com/owncloud/ios/issues/338
We can not reproduce it. Did you do something special on the app before fail (activate instan uploads, share...)? Or you just make login and download and navigate files?

**Comment by miglosh** [comment] 2015-04-22 08:27
Hi @javiergonzper,

I reinstalled the app and it is working fine at the moment. I'll try to reproduce the problem. I did so twice already, unfortunately without knowing the cause. I'll try my best and let you know :-)

**Comment by javiergonzper** [comment] 2015-04-22 08:43
Hi @miglosh 
Do you remember if you set any file as Favorite?  
If you did it the problem was there. We fix a problem related with the favorites that break the download and uploads.
Do not use the Favorites on the iOS app and the app will works fine.

Thanks for your help :)

**Comment by miglosh** [comment] 2015-04-22 08:53
Hi @javiergonzper

you're right, that's the problem. The first favorite works fine. After selecting the second favorite, the app crashes and doesn't do any downloads any more.

So, I'll rather not use favorites for the moment - which is not such a big deal at all.

Thanks for YOUR help ;-)

**Comment by javiergonzper** [comment] 2015-04-22 08:59
Great! Will be fixed on the next release, promise.
You are welcome :+1:

**Closed by javiergonzper** 2015-04-22 08:59 UTC
