### ISSUE TITLE
App losing connection settings and sometimes displays dups after re-entering settings

### ISSUE THREAD

**Issue by codehampster** [owncloud/ios#274] opened 2015-01-20 20:32 UTC
We are using iPad Air 2 devices.  The OS version is 8.1.2 (12B440).

The iOS OwnCloud app version is 3.3.2.

The OwnCloud server we are hitting is running 6.0.3 Stable.

We initially tested the app with no problems.  But now that it is out in the field, we have had 3 users experience issues.

I started the owncloud iOS app.  The initial settings dialog was displayed (like it lost all of the connection configuration info).  

I re-entered the connection information and the app started.

The other symptoms I have seen on one of our systems after the settings were re-entered:

In the root document folder in the owncloud iPad app, I saw two of every folder and document.

If you went into 'Settings' 'Manage Accounts' two accounts for the same login were displayed.

I deleted one of the accounts from within 'Manage Accounts'.  The duplicates still showed.

I stopped the app and restarted it.  The duplicates still showed.

I ended up uninstalling the app and reinstalling it.  Things were then back to normal.

The problem is not propagating itself back to the server (I never ended up with duplicate items there).

In initial testing, I was probably closing the app and turning off the device at the end of the day.  Today when I experienced the issue, the device had been on for several days.  Not sure if this is related to the issue.  But that is one thing that was different.

Thanks,
Richard

**Comment by ggdiez** [comment] 2015-01-29 08:21
Hi @codehampster, 

About the duplicate of the files, that issue has been detected here and will be fixed in the next release. The "duplicate of the files" issue is related with a scenario with bad network bandwidth, the workaround is refresh the view with duplicate files using the pull down gesture.  

About the "re-enter information" when the app started, we are researching the way to reproduce this, we think that can be related with the number of accounts added in the app.

Can you give me more information of that scenario? How many accounts had you set previously? Which account was you using the last time (the order)?

Thank you,

**Comment by codehampster** [comment] 2015-01-29 16:15
Thanks ggdiez, Each of our iPad devices has only one user and the ownCloud iPad app is configured with only one ownCloud account.  So we have only been using that one account.

**Comment by biwerr** [comment] 2015-02-26 13:40
We have the same issue in iOS App v 3.3.3. 
The App shows the Login Dialog, after entering the User Credentials, a second Account is visible under Settings->Accounts.

One of them seems to be empty.I tested it by deleting the second account.

**Comment by javiergonzper** [comment] 2015-02-27 07:21
I am sorry. The version 3.3.3 was a hotfix to support ownCloud 8.
The version that will fix this issue will be the 3.4.0. Right now we are testing that version and will be release soon.

**Comment by codehampster** [comment] 2015-03-02 20:21
Thanks javiergonzper,

I look forward to the release.  We have some pretty frustrated users.  Other than this one issue, the app has worked pretty well.

**Comment by nasli** [comment] 2015-04-09 15:18
Hi @codehampster, could you try with the last version 3.4.1 
You can reopen this issuee if your problems are not solved.
Thanks

**Closed by nasli** 2015-04-09 15:18 UTC
