### ISSUE TITLE
Client does not stay logged in. iPhone 5s/iOS 8.3

### ISSUE THREAD

**Issue by wrst** [owncloud/ios#344] opened 2015-04-15 12:18 UTC
I am running the latest version of the iOS client, updated March 30. I have instant upload enabled. iOS 8.3 running on an iPhone 5s. I am connecting to a Debian server using a self signed certificate, running the latest owncloud from the debian repo on the opensuse build service.

After entering my servers info and login info all works well. When the app falls to the background sometime it will lose all that info and log out. I have to enter the server info and login again. Instant upload of course isn't working due to the logging out.

**Comment by sorenweber** [comment] 2015-04-15 12:21
I am experiencing this too.

**Comment by wrst** [comment] 2015-04-15 12:39
@sorenweber I have done all of that also, only thing I haven't done is a reset of the phone and I'd really prefer not to do that if possible, but if need to for testing purpose can.

**Comment by sorenweber** [comment] 2015-04-15 13:47
@wrst I should have been more clear. What I meant was that I tried the above without success.

**Comment by wrst** [comment] 2015-04-15 16:11
@sorenweber gotcha, I was just trying to say I had tried the same things as you... these darn keyboards need type what I think not what I type :)

**Comment by javiergonzper** [comment] 2015-04-16 09:03
Apple have a bug on the Keychain (the safest place where we store the credentials). By now you can kill the app and open it again.
On the next release we will add a fix to try to resolve it.

**Comment by wrst** [comment] 2015-04-16 11:51
@javiergonzper thanks, that helps and thanks for the response.

**Comment by enoch85** [comment] 2015-08-26 18:35
@javiergonzper Is this fixed?

**Comment by ggdiez** [comment] 2015-08-27 08:51
Hello @enoch85 

With the current version, 3.4.4 , that issue happens less. But still happens. We did some changes to minimize it all of possible.

This issue is related with a Apple keychain problem when the app try to access the credentials data. It's an iOS problem and we will expect that will be fixed in iOS 9.

Instead of enter again the login data the workaround is kill the app and open again. :(

**Comment by ppumkin** [comment] 2015-09-24 09:38
I am still experiencing this issue after updates. I have to type everything in to log in again.
Then when I go to settings, I have 30 accounts,all the same! because I logged in 30 times for example. Can you put a last used account on login or something please?

The issue is still that instantupload stops working after I do it once, or a manual upload to instantuplaod.  Starting to get a bit tedious. :(

**Comment by onewaypub** [comment] 2015-10-02 19:12
Same with iOS 9 and the newest client

**Comment by enoch85** [comment] 2015-10-02 22:34
I can confirm that this issue exist with the latest update. 

iPhone 6, iOS 9
Client 3.4.5
Server 8.1.3

@ggdiez Update here please. :)

**Comment by MikeWW** [comment] 2015-11-01 11:31
I have the same setup as enoch85 (except iPhone 5S) and the ios app has become unusable. 90% of the time it instantly forgets my login details. When it remembers them it often displays two copies of all my files in the list. If I ever get it logged in and then attempt to send anything to it (e.g. a photo from Photos) it allows me to choose a folder and then fails with "Wrong username / password".

I love owncloud but I am going to have to find an alternate solution soon as this is unworkable. It used to function without fault.

If ownCloud is having an issue with a keychain bug maybe you could ask the many other developers of similar apps who have obviously worked around it? I only have this bug with owncloud not any other other app.

**Comment by rperezb** [comment] 2015-11-23 12:30
Done, this will be included within the next iOS versions 3.4.6
Regression test on going on https://github.com/owncloud/ios/tree/release_3.4.6

**Closed by rperezb** 2015-11-23 12:30 UTC
Labels: 5 - To release, Bug, iOS9, login
