### ISSUE TITLE
Error when uploads are disrupted

### ISSUE THREAD

**Issue by Hengjie** [owncloud/ios#556] opened 2016-01-17 19:34 UTC
When I turn on __Instant Upload__ in OwnCloud app in iOS 9.2, it uploads successfully most of the time. However, on occasion if the WiFi or LTE connection is bad and disconnects mid-way through the upload, the upload of that specific image fails perpetually with error __File error__ under __Failed Uploads__ section of the __Uploads__ tab in the app.

Nt: it's definitely not an authentication error as files normally upload fine unless in poor connectivity areas. And it's definitely not a network connectivity error from the server side since I'm monitoring for uptime.

The error logs on the server side says: 

```
{"reqId":"hurzPsIlB8Dl5q6I+Nkb","remoteAddr":"REMOVED","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 405 The resource you tried to create already exists\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\MethodNotAllowed\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(583): Sabre\\\\DAV\\\\Server->createCollection('InstantUpload', Array, Array)\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpMkcol(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:MKCOL', Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(56): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/var\\\/www\\\/owncloud\\\/remote.php(137): require_once('\\\/var\\\/www\\\/ownclo...')\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php\",\"Line\":1154}","level":4,"time":"2016-01-17T19:24:45+00:00","method":"MKCOL","url":"\/owncloud\/remote.php\/webdav\/InstantUpload\/"}
```

However, upon checking if that specific failed file exists in OwnCloud via the OC website on my server, it doesn't exist. If I force a manual upload by going to __Instant Upload__ folder, clicking the "+" in top right, and adding that specific file, then upload works. But that's to be expected because it's technically a new file being uploaded that independent of the instant upload.

I'm posting this in the iOS section because I believe in this case, the iOS app has failed to recover from this server error. Though I'm sure a proper fix would require changes to OC server and iOS client.

I'm running OC iOS version 3.4.6. And OC community server version 8.2.2 (stable).

**Comment by javiergonzper** [comment] 2016-01-18 07:45
Hello @Hengjie thanks for report.
You can see that error when you are working with instant uploads but I think that it is because it is trying to create again the folder "Instant Uploads".
The problem of the "File error" it is because the file that the app is trying to upload do not exist because it was not copied to the file system in order to upload it.
Do you have any other step to reproduce it?

**Comment by rperezb** [comment] 2016-02-11 08:59
this bug is likely to be fixed within the next update, it was related to the keychain and the credentials
If it weren't fixed, please reopen.

**Comment by enoch85** [comment] 2016-03-26 18:21
This is not fixed. 

```
Fatal	webdav	Exception: {"Message":"HTTP\/1.1 405 The resource you tried to create already exists","Exception":"Sabre\\DAV\\Exception\\MethodNotAllowed","Code":0,"Trace":"#0 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(590): Sabre\\DAV\\Server->createCollection('InstantUpload', Object(Sabre\\DAV\\MkCol))\n#1 [internal function]: Sabre\\DAV\\CorePlugin->httpMkcol(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#2 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#3 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(459): Sabre\\Event\\EventEmitter->emit('method:MKCOL', Array)\n#4 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#5 \/var\/www\/owncloud\/apps\/dav\/appinfo\/v1\/webdav.php(55): Sabre\\DAV\\Server->exec()\n#6 \/var\/www\/owncloud\/remote.php(138): require_once('\/var\/www\/ownclo...')\n#7 {main}","File":"\/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","Line":1121,"User":"*****"}	2016-03-26T17:05:06+00:00
```

Server: 9.0
Client: 3.4.8

**Comment by Hengjie** [comment] 2016-03-26 22:31
I've moved away from the iOS entirely so I can't confirm and I'm using [Photo Sync](https://photosync-app.com/) and ownCloud's WebDAV endpoint instead.

**Comment by javiergonzper** [comment] 2016-03-28 09:02
@enoch85 uhm... could be a problem on the server? Because looks like the iOS app can not upload the file because it is there...

**Comment by enoch85** [comment] 2016-03-28 11:43
Yeah actually I think it's server involved here. Let this be open or close?

**Comment by Hengjie** [comment] 2016-03-28 20:02
@enoch85 could you tell me what you did on your side to fix it?

**Comment by enoch85** [comment] 2016-03-28 20:28
@Hengjie It's not fixed, I just reopened it because it fails.

**Comment by rperezb** [comment] 2016-03-29 12:21
@enoch85 how did you reproduce this error?

**Comment by enoch85** [comment] 2016-03-29 12:43
Every time a upload is done. Maybe this issue os not the correct Place for this, but my log is spammed every time with the error log above --^

This issue is in the server for sure, as it's the same behaviour on Android. But maybe you guys could do something about it?

**Comment by rperezb** [comment] 2016-03-29 12:52
@enoch85 what about the desktop client, has it the same issue?

**Comment by enoch85** [comment] 2016-03-29 13:19
Nope, only the iOS and Android client afaik.

**Comment by enoch85** [comment] 2016-03-29 13:20
@rperezb Ok, thanks! Will try when I get some time over, thursday maybe.

**Comment by enoch85** [comment] 2016-04-05 20:34
I haven't seen this latley. Will close.

**Closed by enoch85** 2016-04-05 20:34 UTC
