### ISSUE TITLE
iOS App Sync does not work...?

### ISSUE THREAD

**Issue by marbetschar** [owncloud/ios#499] opened 2015-10-21 15:00 UTC
We've installed a fresh ownCloud 8.2 server and things are working quite well.
There are only a few issues; which I hope you may help out:

[b]1. iOS file downloading in ownCloud app[/b]
Downloading of some files are not working in the ownCloud iOS app:
https://itunes.apple.com/us/app/owncloud/id543672169

It does seem somehow related to the file owner. We have a shared directory "DIR" owned by group "GROUP" shared to user "A" and "B". User "A" now uploads the file XYZ.pdf to "DIR/Produkt/XYZ.pdf".
User "A" can now successfully download XYZ.pdf from the iOS app while user "B" just sees a black screen when opening the file.

**Comment by rperezb** [comment] 2015-10-22 16:53
Hey @marbetschar 
I have not been able to reproduce this error

STEPS:
We have a group, userA, userB and userC are members of this group
1.- UserA shares a folder with group, called DIR
2.- UserB creates a folder on DIR, called "Product" and uploads a a.pdf
3.- UserC access to Dir/Product and downloads a.pdf --> at this stage the download fails?

Are these the right steps?

What device are you using? what is it version?

thx

**Comment by marbetschar** [comment] 2015-10-23 08:50
Hi @rperezb 

Right, these are the correct steps. I just noticed, when I delete the local copy of the file and download it again it seems to work then. Please see the attached screenshots.

What's odd is, that the iOS client doesn't seem to recognize when a previous download failed (or was corrupted anyhow...?) - and therefore does not automatically download the file again.

Instead it just tries to display the corrupted file and - of course - failes in displaying it.
Can you please fix this somehow?

This is how the corrupted file is displayed:
![img_0474](https://cloud.githubusercontent.com/assets/392542/10688299/c62ed548-7973-11e5-870c-0cf9a24bfcf5.jpg)

When I delete the local copy using the trash icon on the bottom right corner, it downloads again and afterwards works:
![img_0476](https://cloud.githubusercontent.com/assets/392542/10688304/cc4560fa-7973-11e5-9c34-587b39821729.jpg)

**Comment by rperezb** [comment] 2015-10-23 09:24
Thanks for checking it!

This is likely to be related to a bug that we have found while developing the download folder feature and, probably have just fixed https://github.com/owncloud/ios/commit/7f78a8fa336be144077dc65e90f14b3ad5992d4b

We'd appreciate if you check it with the next ownCloud iOS version.

**Comment by marbetschar** [comment] 2015-10-23 09:25
Thanks! I'll happily test this on the next version!! Any Idea when it's available?

**Comment by rperezb** [comment] 2015-10-23 09:28
We are currently developing, we plan to freeze the code around 15 Nov, this is just an estimation

**Comment by marbetschar** [comment] 2015-10-23 09:32
Ok; is there any possibility to verify this issue is really resolved before then?
To prevent it pop's up then again?

**Comment by rperezb** [comment] 2015-11-05 08:00
@marbetschar what you may do, ftm, it´s download the code and compile the develop branch.

I close this issue since it´s been fixed https://github.com/owncloud/ios/commit/7f78a8fa336be144077dc65e90f14b3ad5992d4b and it will be released within the next ownCloud iOS version. If it didn't work for you, please reopen

**Closed by rperezb** 2015-11-05 08:00 UTC
Labels: Bug, download
