### ISSUE TITLE
Bug: files not downloading immediately

### ISSUE THREAD

**Issue by tushevorg** [owncloud/ios#367] opened 2015-05-18 21:06 UTC
When I tap on a file the download does not start immediately: a progress bar appears, but it never moves.

Minimizing app and restoring for several times suddenly makes all such files start downloading.
The app often crashes immediately after that.

This bug is very annoying.

iOS 8.3, bug appears on both iPhones and iPads. Both on WiFi and cellular.
Client ver 3.4.1

**Comment by rperezb** [comment] 2015-05-19 07:21
Thanks for reporting this. 
A new version, 3.4.2, will be released soon, it is pending Apple approval,  in this version we have included a fix related to the downloads. We'd appreciate if you check it and let us know whether this fixes your issue.
thx

**Comment by rrmac1912** [comment] 2015-06-24 14:57
Any idea when 3.4.2 might be available in the App store?  Now mid June and the App store version is still at 3.4.1 and this bug still exists.

**Comment by MTRichards** [comment] 2015-06-24 15:08
Hi @rrmac1912 Apple has rejected the app 5 times, all for meta data reasons. Funny story, the meta data is not changed. Anyway, it is back in as 3.4.3 and hopefully ready in the next 10 days, dependent on apple.

**Comment by tushevorg** [comment] 2015-07-14 07:02
Hi @MTRichards , how is the review going?

**Comment by rperezb** [comment] 2015-07-14 08:36
Hi @tushevorg we expect it to be approved this week.
The new version will be 3.4.4
Thanks for your understanding.

**Comment by MTRichards** [comment] 2015-07-17 22:46
Well, sadly - they rejected it again. This time because they misread the credentials on our test instance for them to try the app. While I have a lot of patience, it is wearing very thin at the moment...It has been resubmitted making the username / password (which they managed to figure out for the last 3 years, but somehow can't figure out now) clearer for them.

**Comment by tushevorg** [comment] 2016-04-01 09:13
This still happens. I manage to circumvent this by sharing the file and opening it in browser, but this all is VERY inconvenient. 

now - iOS 9.3, owncloud/ios 3.4.8, oc/server 8.2.2

**Comment by rperezb** [comment] 2016-04-01 09:33
@tushevorg any error logs on the server? certainly, this is something that we don't reproduce neither we have received other complains

**Comment by tushevorg** [comment] 2016-04-01 09:52
Error logs are mostly empty. Attaching the only line that appeared.
Access log attached as well

[access.txt](https://github.com/owncloud/ios/files/199358/access.txt)
[owncloud.error.log.txt](https://github.com/owncloud/ios/files/199360/owncloud.error.log.txt)

**Comment by nasli** [comment] 2016-08-26 07:45
Still an issue?
@tushevorg could you check with latest 3.5.0?
If needed reopen, please. Thanks!

**Comment by tushevorg** [comment] 2016-10-10 10:16
Hi @nasli , sorry for late answer.

Just did fresh install of 3.5.1 on iOS 10.0.1. The problem persists. 

Any suggestions how to solve it? Possibly mis-configured server or what?

**Comment by tushevorg** [comment] 2016-10-10 10:49
One more update: if I leave the file "downloading" and leave the phone so it locks itself, then re-unlock it after 10mins or so, the file will be downloaded.

As well, I have Background updates off

**Comment by nasli** [comment] 2016-10-10 11:29
Which are the current steps? You can not download anything? Could you detail more? Thanks

**Comment by tushevorg** [comment] 2016-10-10 18:29
@nasli ,

I go to the file I want to download:
![photo-2016-10-10-23-04-56_1815](https://cloud.githubusercontent.com/assets/5861233/19246177/7cc503d2-8f3e-11e6-8039-a66214d92325.png)

Then I tap on it:
![photo-2016-10-10-23-05-04_1816](https://cloud.githubusercontent.com/assets/5861233/19246175/7cc070ba-8f3e-11e6-9762-984eb8c3496b.png)
Nothing happens here. Download bar never moves. This can be for a very long time.
This is what nginx log says:

> [10/Oct/2016:14:13:00 -0400] "PROPFIND /o/remote.php/webdav/iOS/ios_security.pdf HTTP/2.0" 207 1398 "-" "Mozilla/5.0 (iOS) ownCloud-iOS/3.5.1"
[10/Oct/2016:14:13:04 -0400] "GET /o/remote.php/webdav/iOS/ios_security.pdf HTTP/2.0" 200 913282 "-" "Mozilla/5.0 (iOS) ownCloud-iOS/3.5.1"
[10/Oct/2016:14:13:15 -0400] "PROPFIND /o/remote.php/webdav/ HTTP/1.1" 207 376 "-" "Mozilla/5.0 (Windows) mirall/2.2.4 (build 6408)"

If I go back I see:
![photo-2016-10-10-23-05-07_1817](https://cloud.githubusercontent.com/assets/5861233/19246176/7cc43538-8f3e-11e6-84e9-a3b6c171be98.png)
Same here, the file is not being downloaded...
And this goes to the log when I press back:
> [10/Oct/2016:14:13:32 -0400] "GET /o/ocs/v1.php/apps/files_sharing/api/v1/shares?path=iOS/&subfiles=true HTTP/2.0" 200 626 "-" "Mozilla/5.0 (iOS) ownCloud-iOS/3.5.1"
[10/Oct/2016:14:13:32 -0400] "PROPFIND /o/remote.php/webdav/iOS/ HTTP/2.0" 207 1426 "-" "Mozilla/5.0 (iOS) ownCloud-iOS/3.5.1"

owncloud.log is empty.


Nginx GLOBAL error log says:

> 2016/10/10 14:25:18 [error] 14001#14001: OCSP_basic_verify() failed (SSL: error:27069065:OCSP routines:OCSP_basic_verify:certificate verify error:Verify error:unable to get local issuer certificate) while requesting certificate status, responder: ocsp.startssl.com

The other services on the server use client TLS authentication, nginx.conf says:
>     ssl_verify_client			optional;

Could TLS client authentication be the source of problem?

**Comment by tushevorg** [comment] 2016-10-10 18:34
Oh yes, it could! I temporarily disabled it and everything worked like a charm. After I re-enabled it, the problem persists again.

So at least now we know what is the cause of the problem. Can we fix iOS app to support such cases?

BTW, iOS app is capable of browsing files with client TLS auth, but cannot download any of them. Windows app handles both situations correctly.

**Comment by nasli** [comment] 2016-10-11 07:58
Thanks for the update @tushevorg, We  will check it, if you could provide us a test account of your server to apps@owncloud.com, that would help .  Thanks!

**Comment by jesmrec** [comment] 2016-10-24 09:13
@tushevorg if you send the test account to the email address that @nasli told, please ping us here. Thank you.

**Comment by tushevorg** [comment] 2016-10-24 16:24
@jesmrec I did not send the credentials yet. That server is not available from Internet. I'm going to set up a demo server with the same configuration very soon and I will let you know.

**Comment by tushevorg** [comment] 2016-10-24 18:16
@nasli @jesmrec I've set up the demo server. The issue persists here as well, so it's not server-specific. I've sent an email with credentials. Thanks!

**Comment by jesmrec** [comment] 2016-10-25 11:23
@tushevorg I have reproduce the problem with your server. Thanks!

@nasli I have gathered some logs related when a download is performed from iPhone or iPad. The logs stops here (the last logs before stopping):

`Oct 25 13:14:44 Solids-iPad nsurlsessiond[113] <Error>: Application com.owncloud.iOSmobileapp is not handling a background URLSession but we still received a signal to deliver pending events
Oct 25 13:14:44 Solids-iPad Owncloud iOs Client[2799] <Warning>: <0x124e18910 RecentViewController.m:(303)> Recent normal uploads: 0
Oct 25 13:14:47 Solids-iPad Owncloud iOs Client[2799] <Warning>: <0x100497ca0 ManageFilesDB.m:(1547)> getFilesByDownloadStatus: -1`

**Comment by davivel** [comment] 2016-12-01 09:56
Sorry, @tushevorg , but we need to delay this bug to the next release.

**Comment by tushevorg** [comment] 2016-12-01 13:13
@davivel Ok. Do you need any assistance?

**Comment by davivel** [comment] 2016-12-05 12:06
@tushevorg , do you mean fixing it? Do you develop iOS apps? Code contributions are always welcome :)

**Comment by jesmrec** [comment] 2017-02-20 09:30
@tushevorg 

a new release was launched recently (3.5.3), could you check if the problem persist or is fixed? i tried to check it with the test account but it was already disabled.

In your first post, you wrote that the problem is reproducible with iOS 8.3. From this version 3.5.3 only versions 9 and later and supported (only for you to know).

**Comment by tushevorg** [comment] 2017-03-03 17:32
@jesmrec Sorry for the delay. I have re-enabled the test server. Please check it.

**Comment by tushevorg** [comment] 2017-03-03 17:42
The problem still perists. I'm running ownCloud 9.1.1, ownCloud App 3.5.3 on iOS 10.2.1.

**Comment by tushevorg** [comment] 2017-03-04 16:26
@jesmrec 

I have also created another web server that does not request for client TLS certificate. I've sent credentials to apps@ownloud.com.
It's actually the same server, the only difference is that this new server does NOT have

    ssl_client_certificate       /etc/.../owncloud.ca.crt;
    ssl_verify_client            optional;   
	
in nginx config, while the first one has those line. The bug appears on the old server, but not on the new one. Hope this helps with debugging.

P.S. Please do not post actual server names here in this thread. :)

**Comment by davivel** [comment] 2017-04-11 15:07
Hi, @tushevorg . The origin of you problem is that the iOS app does not support verification of SSL client certificate.

Please, track any progress of that topic in #222 .

Thanks,

**Closed by davivel** 2017-04-11 15:07 UTC
Labels: Bug, sev2-high
