### ISSUE TITLE
Instant Upload not working (at all)

### ISSUE THREAD

**Issue by jschwalbe** [owncloud/ios#573] opened 2016-01-28 17:06 UTC
### Expected behavio(u)r
I'm at Disney World with the family - taking lots of pictures. Walking around making lots of significant changes in geography. I expect that the pics/videos should be on my ownCloud server under the _InstantUpload_ folder. (It did work exactly once.)

### Actual behaviour
When I get home to the condo after a day of walking around the theme park, I open my ownCloud to find that **none** of the pictures or videos have transferred. I've tried force quitting the app and reopening. I've tried logging out and back in. I've even deleted the account and readded it (after generating a valid  certificate (signed by LetsEncrypt). After each of these steps, I've taken new pictures but they don't reliably upload.
Of note, I also use Google Photos, and it hasn't been uploading photos in the background - not until I open the app. But at least it uploads them when I open the app, ownCloud doesn't do that currently. :(

### Steps to reproduce
1. Take pictures of beautiful family. (Find a substitute if yours isn't beautiful enough.)
2. Walk around Magic Kingdom.
2.5. Buy some popcorn for the kids.
3. Look at ownCloud and make a sadface because it hasn't uploaded any new pics. And it doesn't start after launching the app, either.

### Environment data
• iPhone 6. 16GB data (_of note, the storage on the iPhone is routinely fairly full_ -- could this be part of the problem? After reading thru many of the issues/comments around Instant Upload I understand it makes a copy of photos before uploading.). 
• iPhone is locked automatically at one minute, requires TouchID to unlock.
• iOS version: 9.2. (Not jailbroken.)
• ownCloud iOS app version: 3.4.6* 
         * built via XCode from github via instructions found elsewhere (made a fork, cloned it, changed the Bundle IDs and Group Name) -- _Off topic, but are there instructions on how to download the latest code without having to make the bundle and group name changes each time? I like to test the most recent code without waiting for the App Store._
• App does have access to photos (I can select individual photos from camera roll and upload them without issues.)
• Background App Refresh - **On** in general and **On** for the ownCloud app.
• Privacy -> Location Services - **On**. ownCloud is set to **Always**

### Random thoughts/questions/ideas associated with this report
1. I know it uses "more resources" but is there a reason we couldn't have the ownCloud server push a request to the client every x minutes to check for new photos instead of relying on GPS changes?  (That being said: my GPS certainly is changing and that doesn't seem to matter.)
2. Is there an easy command to update to the newest dev tree on my computer so I can rebuild the iOS app?

As always, thanks devs for the hard work! It's a great product.

**Comment by javiergonzper** [comment] 2016-02-01 13:11
Thanks for report. We will check it :+1:

**Comment by mRoRo** [comment] 2016-02-18 11:50
Hello @jschwalbe ,

We've reviewed your issue and we couldn't reproduce it. After taking the photos, if they app is not able to upload them, you should see these photos in OC "uploads" view, under "Current" section with the message "Waiting to upload". Please check it. However, it's necessary to have the storage capacity to copy the photos as you supposed.

About your Random thoughts/questions/ideas:

1. We don't support push notifications at the moment. You can open an issue for this enhancement.

2. In order to update to the newest dev tree, in your local fork you can change the Bundle IDs and Group Name. Then, you can commit and push this changes and update your local branch with the remote branch you want to use. Have a look at : [(https://help.github.com/articles/syncing-a-fork)/]. You can get in master branch the current app store version (3.4.6) and in develop branch what we have lately developed.

**Comment by HanSooloo** [comment] 2016-05-17 03:37
Running into same problem on iOS app, version 3.4.9. Tried on iPad mini 2.

No combination of app kill, instant upload on/off toggle works. 

Of worthy mention is that THE FIRST TIME instant upload is enabled, app causes iOS to ask for 2 permissions. After I grant them, app pops a "couldn't access your photos, please allow access" error message. After that instant upload toggle remains in off position. 

But, then, you can tap the instant upload icon again, and this time it sticks. However, nothing uploads.

**Comment by jschwalbe** [comment] 2016-05-17 11:32
@HanSooloo just curious how much space is avail on your device? Do you get warnings frequently of low space (like I do?)? Wonder if that's at play. 
I've had to shut off my server for a bit so haven't had a chance to do further testing.

**Comment by enoch85** [comment] 2016-08-19 13:20
Is this fixed in 3.5.0?

**Comment by Jon-Schneider** [comment] 2016-08-19 13:22
@enoch85 Instant Upload in 3.5.0 made it through pretty heavy regression testing.

**Comment by nasli** [comment] 2016-08-19 13:31
@enoch85 all test cases performed with instant uploads have been passed successfully.
3.5.0 expected for next week.

**Closed by nasli** 2016-08-19 13:31 UTC
Labels: Bug, Instant uploads

**Comment by enoch85** [comment] 2016-08-19 13:34
I really hope video upload comes soon. :)

**Comment by nasli** [comment] 2016-08-22 11:35
@enoch85 Instant uploads for video too within today released 3.5.0 :)

**Comment by enoch85** [comment] 2016-08-22 11:36
Great news!
