### ISSUE TITLE
isURLWithSamlFragment hardcoded url fragments

### ISSUE THREAD

**Issue by felixboehm** [owncloud/ios#749] opened 2016-07-29 10:18 UTC
`isURLWithSamlFragment(url)` has hardcoded strings to detect from URL if speaking to an IDP.
https://github.com/owncloud/ios/blob/master/Owncloud%20iOs%20Client/Utils/FileNameUtils.m#L258

This doesn't work out for existing infrastructures. 
Failing example:
- F5 loadbalancer, redirects (302) to location `/my.policy`, results in url like `https://sso.mycloud.com/my.policy` "Redirected to an unsecure route"

Android Client is not doing this check.

@nasli @rperezb @michaelstingl

**Comment by rperezb** [comment] 2016-07-29 10:20
@davivel fyi

**Comment by davivel** [comment] 2016-07-29 10:23
Joining to the party. So, the problem is for a deployment where we have both SAML redirections and "regular" redirections to follow. In Android we had to deal with this specifically, let's have a look.

**Comment by nasli** [comment] 2016-08-02 08:51
This will be fixed within nex release 3.5.0

**Closed** 2016-08-19 08:46 UTC
Labels: 5 - To release
