### ISSUE TITLE
5S App won't work

### ISSUE THREAD

**Issue by Froster** [owncloud/ios#338] opened 2015-04-09 07:17 UTC
Hello,

after i installed the OC App on my 5S i could upload and download aprox 10-20 Files after that no file couldn't anymore up- or download. Only nothing will happen.

Functions like move files or create folders will work ever.

I can reproduce it every time, uninstall the app install it new download a couple of files and then the app stucks.

Over the same time web ui and iPad app work correctly without any issues.

App Version: 3.4.1
iPhone 5S
iOS Version 8.2

Server Version 8.0.2

**Comment by javiergonzper** [comment] 2015-04-09 07:22
Hi @Froster 
If you kill the app and open it again the app works again?

**Comment by Froster** [comment] 2015-04-09 07:27
Hi,

no nothing even restart the phone won't help. Only new install or delete all accounts.

**Comment by javiergonzper** [comment] 2015-04-09 09:06
I am trying to reproduce the problem on an iPhone 6 with 8.3 and Server version 8.0.2 but I can not.
Sometimes I got a crash related with the progress but after open the app again the downloads and uploads works fine.

**Comment by Froster** [comment] 2015-04-09 09:07
Christian Bremm schrieb am 09.04.2015 11:07
_____________________________________________________________________

On iPhone 4/4s we also have no issues.

 

Maybe i try 8.3 ?

 

Freundliche Grüße  

SIEGENIA GRUPPE
Geschäftsbereich Management & Support   

i. A.   

Christian Bremm

EDV / SAP-CC / BC

 

Tel.: +49 6503 917-303

Fax: +49 6503 917-190

E-Mail: christian.bremm@siegenia.com 

Internet: http://www.siegenia.com 

 

Von: Javier Gonzalez [mailto:notifications@github.com] 
Gesendet: Donnerstag, 9. April 2015 11:06
An: owncloud/ios
Cc: Bremm, Christian MDV-H
Betreff: Re: [ios] 5S App won't work (#338)

 

I am trying to reproduce the problem on an iPhone 6 with 8.3 and Server version 8.0.2 but I can not.
Sometimes I got a crash related with the progress but after open the app again the downloads and uploads works fine.

—
Reply to this email directly or view it on GitHub <https://github.com/owncloud/ios/issues/338#issuecomment-91163821> . <https://github.com/notifications/beacon/ACqrrr-FYIwk8aqCLLA6sao4UwUZidi4ks5n9jh-gaJpZM4D9B7h.gif> 

We like trees. Print me only if you need me. Thank you.

_________________________________
SIEGENIA-AUBI KG, Industriestraße 1 - 3, 57234 Wilnsdorf-Niederdielfen
Kommanditgesellschaft, persönlich haftender Gesellschafter: Wieland Frank, Sitz der Gesellschaft: Wilnsdorf,
Registergericht: Amtsgericht Siegen, HRA 3741

Der Inhalt dieser E-Mail und etwaige Anhänge sind vertraulich und können urheber-, patent- oder in anderer Weise
rechtlich geschützt sein; sie sind deshalb ausschließlich für den bezeichneten Adressaten bestimmt. Sollten Sie nicht
der bezeichnete Adressat dieser E-Mail oder dessen Vertreter sein, so beachten Sie bitte, dass jede Form der
Kenntnisnahme, Veröffentlichung, Vervielfältigung, Weitergabe oder Nutzung des Inhalts dieser E-Mail oder der
Anhänge unzulässig ist. Wir bitten Sie, sich in diesem Fall mit dem Absender der E-Mail in Verbindung zu setzen und
jegliche Originale und Kopien der E-Mail und der Anhänge zu vernichten. Wir weisen ausdrücklich darauf hin, dass die
E-Mail-Kommunikation über das Internet unsicher ist, weil unberechtigte Dritte grundsätzlich die Möglichkeit der
Kenntnisnahme und Manipulation haben.

**Comment by zooomak** [comment] 2015-04-09 13:07
Same here:
https://twitter.com/zumak/status/586147153485160448/photo/1

iOS 8.2.
App 3.4.1.
ownCloud 7.0.1 (stable)

**Comment by Froster** [comment] 2015-04-09 14:20
Also in iOS App Store there is at least one review pointing on an issue with 5s, which is not mine.

**Comment by javiergonzper** [comment] 2015-04-10 07:37
@Froster @zooomak  After update to 8.3 still happening?
I can not reproduce it but I found a crash related to tu put many files to download (images) and wait. Could be related with your bug.

**Comment by Froster** [comment] 2015-04-10 08:28
@javiergonzper 

after I installed 8.3 i could download aprox 7-8 files (2-3 pics, 2 pdfs, 3 xls) then during loading another xls the app crashed and closed itself.

And now same as before. Couldn't download anything even restarting the app or ios won't help.

Maybe it is a issue regarding XLS? files i have a lot.

**Comment by javiergonzper** [comment] 2015-04-10 08:46
I think that it is not be related only with the XLS but it is exactly the problem that I resolve a few minutes ago here https://github.com/owncloud/ios/tree/downloading_files_crash_progress
After download several files (and probably upload also) the app crash.

The fix will be on the next release :+1:

**Comment by Froster** [comment] 2015-04-10 08:55
thx

when will the release be public? is there anything known?

**Comment by javiergonzper** [comment] 2015-04-10 09:03
No idea sorry... we plan to add on the next release many things but we did not plan when will be.

**Comment by Froster** [comment] 2015-04-10 09:07
ok is there any Chance to test it? i can explain why im so highly interested but not here in public..

**Comment by javiergonzper** [comment] 2015-04-10 09:08
You can contact us on apps@owncloud.com and explain it :wink:

**Comment by Froster** [comment] 2015-04-10 09:10
DOne

**Comment by vain90** [comment] 2015-04-13 13:56
I have the same Problem.

I use a iPhone 5s.
A fresh new installation works absolutely fine.
But, in my case, if i close the app completely (double tap on home and close) I can't up or download anything.

![fullsizerender](https://cloud.githubusercontent.com/assets/11925757/7116918/984cf288-e1f5-11e4-9868-26eadc64751c.jpg)

**Comment by javiergonzper** [comment] 2015-04-14 08:55
@vain90  Everything works fine until you kill the app?

**Comment by vain90** [comment] 2015-04-14 09:00
@javiergonzper Correct. After that only helps to reinstall.

**Comment by javiergonzper** [comment] 2015-04-14 09:03
Ok, I will check it, thanks! :+1:

**Comment by javiergonzper** [comment] 2015-04-16 09:05
@vain90 witch version of iOS are you using? do you have any upload/download in progress when you kill the app?

**Comment by vain90** [comment] 2015-04-16 09:25
@javiergonzper current iOS-Version is 8.3 but the previous version has the same problem.
The App-Version is 3.4.1 but the problem was also in versions befor.

No, if i use a fresh new installation all my down or uploads are finisched befor i killed the App. (App Kill is my way to close "not used Apps") But after i killed the App i can no more up or download. BUT i can see my offline files. (tagged with a star). I can also go into a subfolder.

**Comment by vain90** [comment] 2015-04-20 21:23
Is it possible that it is a server problem? You have referenced the issue#351 and you are not able to reproduce. I can offer to set up a test account on my OwnCloud.

**Comment by Froster** [comment] 2015-04-21 07:17
All issues i see here came from Germany?

**Comment by vain90** [comment] 2015-04-21 07:33
I think so. According to the picture miglosh from issue#351 is from Germany.
zooomak has written german bug report on twitter.

@javiergonzper I have send you an email (javiergonzper@gmail.com) with two error messages.

**Comment by javiergonzper** [comment] 2015-04-21 09:28
ownCloud is very popular at Germany :)

@vain90 I saw the mail. Those logs appear when you try to download something or just when you open the app?

**Comment by vain90** [comment] 2015-04-21 10:07
@javiergonzper I have just seen that there was not a error entry. It is a Debug entry =) But i see this message only when I open the App on the iPhone. When I try to download anything, I see no other entry in the log.

I think I've found a way to reproduce the problem.
A new installation works correctly as long until I select a file to my favorites and close/kill the App. As long as I do not select a file to my favorites everything works great. Even after I close/kill the app and open again. But as soon as a file is marked as a favorite and then I close my app I have the problem.

The account on my server I send to the specified email address. But before I go lunch. I send the email after that. =)

**Comment by javiergonzper** [comment] 2015-04-21 10:42
Hey @vain90 thats are the steps! We can reproduce it all the time.
I will start to fix it now.
Thanks!

**Comment by cdamken** [comment] 2015-04-22 13:34
I talked with @Froster and we can confirm the problem was solved.

# Thanks Guys

**Closed by cdamken** 2015-04-22 13:34 UTC

**Comment by javiergonzper** [comment] 2015-04-22 13:37
:+1:
