### ISSUE TITLE
Tapping on settings button Giving Exception..

### ISSUE THREAD

**Issue by harithahdasan** [owncloud/ios#462] opened 2015-09-04 09:38 UTC
When I click the settings tab of own cloud  ,app is throwing exception...

2015-09-04 15:04:10.506 Owncloud iOs Client[2326:1382609] <0x38f040 OCKeychain.m:(80)> (getCredentials)Error Code -25300
2015-09-04 15:04:10.507 Owncloud iOs Client[2326:1382609] Unable to get the item with id =1 
2015-09-04 15:04:10.518 Owncloud iOs Client[2326:1382609] Account cell username:(null)
2015-09-04 15:04:10.527 Owncloud iOs Client[2326:1382609] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSCFConstantString stringByReplacingOccurrencesOfString:withString:options:range:]: nil argument'

How to resolve this issue.Please help

**Comment by nasli** [comment] 2015-09-04 11:50
Hi @harithahdasan, the following links can help you to set up xcode and all certificates:
https://github.com/owncloud/ios/blob/develop/SETUP.md
https://github.com/owncloud/ios/blob/develop/OCC2015_iOS_workshop.pdf
#407

**Comment by harithahdasan** [comment] 2015-09-04 12:07
I have done all those things...But still the same exception.....
Below is the more details regarding exception...

2015-09-04 16:54:26.915 Owncloud iOs Client[2440:1410287] Unable to get the item with id =3 
2015-09-04 16:54:26.919 Owncloud iOs Client[2440:1410287] <0x2b8230 OCKeychain.m:(76)> keychainItem: {
    acct = 4;
    agrp = "Z6C73S6JM5.group.com.qualicloud.iosapps";
    class = genp;
    pdmn = ck;
    "r_Attributes" = 1;
    "r_Data" = 1;
}

**Comment by nasli** [comment] 2015-09-04 12:26
Try to clean the iOS simulator, In the iOS Simulator menu select "Reset content and settings"

**Comment by harithahdasan** [comment] 2015-09-04 12:32
Wot about device?

**Comment by rperezb** [comment] 2015-09-07 07:14
Thanks @harithahdasan for contacting us.

The issue that you are reporting seems to be related to how you have created the needed certificates to compile the app; the error shown is related to the keychain.

What we may suggest you is to follow the instruction on: https://doc.owncloud.com/server/8.0/admin_manual/enterprise_clients/index.html

The issue is not related to the device neither to the simulator but when the generation of the needed certificates.

**Comment by harithahdasan** [comment] 2015-09-07 12:01
ok thankyou

**Comment by rperezb** [comment] 2015-11-25 08:45
This should be fixed, if not, please reopen

**Closed by rperezb** 2015-11-25 08:45 UTC
