### ISSUE TITLE
[3.5.0] "Live Photo" cause errors in instant uploads

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios#746] opened 2016-07-26 16:30 UTC
Enabling the "Live Photo" feature in the iPhone6S camera, and taking one pic:

- The pic is uploaded twice:

<img width="403" alt="screen shot 2016-07-26 at 18 20 46" src="https://cloud.githubusercontent.com/assets/14894746/17146324/4a688326-535e-11e6-9159-2566644122ea.png">

- One of the uploaded files is repeated some more times, so several conflicts are detected. One of them is shown as file error:

<img width="400" alt="screen shot 2016-07-26 at 18 21 05" src="https://cloud.githubusercontent.com/assets/14894746/17146374/8190b706-535e-11e6-8019-e381f037b03e.png">

iOS version: 9.1

cc @nasli @Jon-Schneider

**Comment by nasli** [comment] 2016-07-27 06:34
We should check this within release, it is a regression, previous version uploaded just one photo. Since this is an iOS important feature that user use, I don't want to upload all my photos duplicated 
Could you check it @Jon-Schneider , Thanks!

**Comment by Jon-Schneider** [comment] 2016-07-27 20:43
@nasli I can take a look, possibly as soon as tomorrow.

**Comment by Jon-Schneider** [comment] 2016-07-28 23:36
What it looks like is happening is the live photos are being modified for some reason by the system a a few times (usually twice, maybe always twice) after being created, resulting in an updated modification date that causes them to be reuploaded if you started to upload the before that modification took place.

Possible Solutions:
1. Switch back to using creation date rather than modification date for instant uploads. Edited photos will no longer be uploaded. Dropbox appears to use creation date - I downloaded the app and started modifying some static and live photos and none of the edited images were uploaded. I personally am striving to create a better product than Dropbox's Instant Upload feature but it is telling that a lot of really smart people who work on this full time have gone with this.

2. There is one other possibility: We cannot fetch separate asset types in separate fetch requests and still only get camera roll assets in a good, convenient way, at least not in a way that's obvious to me. However, we could possibly fetch each of the 5 PHAssetMediaSubtypes that relate to images (https://developer.apple.com/library/ios/documentation/Photos/Reference/Photos_Constants/index.html#//apple_ref/doc/c_ref/PHAssetMediaSubtype) with a separate fetch request with live photos fetched based on creation date and all other photos (normal, HDR, Panoramic, and Screenshot) based on modification date and then uploading them. Requires five fetch requests per upload and inconsistent behavior between asset types, but it's a possibility.

**Comment by jesmrec** [comment] 2016-07-29 06:23
At this point, we are very close to release a new version. So, if the problem was caused by the upload of edited pics, a rollback of that feature solves the problem. After the release, we will work again to figure out the best solution.

**Comment by nasli** [comment] 2016-07-29 06:46
Great @Jon-Schneider , thanks for check it out, as @jesmrec, lets move to the creation date again and think how the better way to upload live photos and edited ones

**Comment by nasli** [comment] 2016-07-29 06:53
Related to Live photos https://github.com/owncloud/ios/issues/578

**Comment by nasli** [comment] 2016-08-19 08:43
This will be fixed within 3.5.0 release. 

To support live photos let's continue tracking here #578

**Closed** 2016-08-19 10:56 UTC
Labels: 5 - To release, Bug, Instant uploads
