### ISSUE TITLE
Cloud Integration in iOS "Locations" Menu

### ISSUE THREAD

**Issue by miqrogroove** [owncloud/ios#362] opened 2015-05-12 17:37 UTC
MS Office v1.9.2 for iOS is out and claims to offer full "open, edit, and save" in online storage services.  Indeed, it now allows saving to iCloud.  However, the ownCloud app 3.4.1 interface appears to be broken or incomplete.  The Locations menu has a More option with an on/off switch for ownCloud, but there is no way to select ownCloud as the location to save a file.

**Comment by tflidd** [comment] 2015-05-12 18:07
Like the user demonstrated in this issue: https://github.com/owncloud/ios/issues/361 ?

**Comment by RealRancor** [comment] 2015-05-12 18:07
Hi,

isn't this a duplicate of: https://github.com/owncloud/ios/issues/361 ?

**Comment by miqrogroove** [comment] 2015-05-12 18:59
The locations menu looks just like that in Office too, yes.  :)

**Comment by miqrogroove** [comment] 2015-05-12 19:05
The problem is different though.  In Office, I can open documents but not save.  That other ticket was about opening files.

**Comment by javiergonzper** [comment] 2015-05-18 10:31
Hi @miqrogroove 
I just tested the Word app opening a document from an ownCloud server. I edited it and later I open the ownCloud app and the file modified started to upload at the moment.
Did you open ownCloud after edit your file?

**Comment by miqrogroove** [comment] 2015-05-18 13:12
I am unable to save Word documents to ownCloud.  Therefore, I have no Word documents on the server.  Therefore, the answer is no, I have never done that.

**Comment by javiergonzper** [comment] 2015-05-19 08:54
Oh I see. I tested the Document Provider opening an existing .docx document but if you create a new document on Word you can not upload the file to ownCloud because the option "Export" is not implemented and looks like it is the option of t he Document Provider that you need to send the document to ownCloud.

We will check it. Thanks for report @miqrogroove

**Comment by ggdiez** [comment] 2015-06-19 08:27
We are currently developing export and move option on document provider in #389. With this two modes ownCloud could work with word.

**Closed by ggdiez** 2015-06-19 08:27 UTC
Labels: Enhancement

**Comment by TC2Wheels** [comment] 2016-03-09 18:31
We are running 8.2.2.  When an IOS 3.8.4 client opens a Microsoft Word document it is read-only and it does not appear that OwnCloud has been added as a cloud provider.  Can you please assist?
