### ISSUE TITLE
File error appears sometimes in uploads

### ISSUE THREAD

**Issue by nasli** [owncloud/ios#761] opened 2016-08-24 07:33 UTC
### Steps to reproduce

1.Select to upload some photos
### Expected behaviour

All photos are uploaded
### Actual behaviour

Some uploads fail with file error
### Client

**iOS version:** 9.3

**ownCloud app version:** 3.5.0

**Device model** iphone 6
### Logs

File before request, file does not exist

**Comment by rperezb** [comment] 2016-08-24 12:18
Related to https://github.com/owncloud/enterprise/issues/1507

**Comment by enoch85** [comment] 2016-09-09 17:00
Can confirm this.

**Comment by enoch85** [comment] 2016-09-09 17:02
Happens on instantuploads as well.

**Comment by nasli** [comment] 2016-09-13 13:09
Hi @enoch85, could you provide us more information?
Device model, iOS version, size of image that fail with message "File error", Settings enabled in your app, server, size available in your device.
Are you using multiaccount? 
Some steps to reproduce would be great. Thanks!!

**Comment by rperezb** [comment] 2016-09-22 07:33
@ggdiez fyi

**Comment by enoch85** [comment] 2016-09-24 14:07
@nasli 

Unfortunately I don't keep track of every upload, so steps to reproduce is not possible, sorry.

Regarding the other stuff, here you go:

### Steps to reproduce
1.Select to upload some photos

### Expected behaviour
All photos are uploaded

### Actual behaviour
Some uploads fail with file error

### Client
**iOS version:** 9.3.5

**ownCloud app version:** 3.5.0

**Multiaccount**
No

**Device model** iphone 6

### Logs
File before request, file does not exist

## Server
Ubuntu Server 16.04.1
MysQL 5.7
Apache 2.4
PHP 7

## File size 
Various file sizes, all from 500 KB to 20 MB

**Memory Available in Phone**
5 GB (Though it could be that there was little available memory when this occurred, still it shouldn't produce a file error - it should retry the file again if it fails due to low memory)

## Settings
Instant Upload - YES
Background Instant Upload - YES

**Comment by frank9999** [comment] 2016-09-24 19:37
I also encounter the "file error" upload fail. I'm using ownCloud iOS app version 3.5.0 on iOS 9.3 and iOS 10.

The interesting part is that I'm able to reproduce the "file error" with version 3.5.0 and not with 3.4.9. Version 3.4.9 uploads all images fine, but with 3.4.9 the images which fail on 3.5.0 are not visible in the upload file picker.

Would it be possible for you to downgrade to 3.4.9 and confirm that those failed uploads are not available in the upload file picker?

Debug log app version 3.5.0:
2016-08-12 16:10:41.606 Owncloud iOs Client[262:11701] <0x13086d770 ManageUploadRequest.m:(230)> self.currentUpload: Photo-2016-07-22-17-35-28_3989.JPG2016-08-12 16:10:41.608 Owncloud iOs Client[262:11701] localSource: /private/var/mobile/Containers/Shared/AppGroup/18049616-162A-4784-ADE4-F5AE06ED5D62/cache_folder/temp/Photo-2016-07-22-17-35-28_3989.JPG2016-08-12 16:10:41.609 Owncloud iOs Client[262:11701] remoteDestination: https://xxx/remote.php/webdav/Photo-2016-07-22-17-35-28_3989.JPG2016-08-12 16:10:41.610 Owncloud iOs Client[262:11701] <0x13086d770 ManageUploadRequest.m:(407)> _startUploadFile_ Photo-2016-07-22-17-35-28_3989.JPG from /private/var/mobile/Containers/Shared/AppGroup/18049616-162A-4784-ADE4-F5AE06ED5D62/cache_folder/temp/Photo-2016-07-22-17-35-28_3989.JPG to https://xxx/remote.php/webdav/, fails before request (File not exist). Error: Error Domain=com.owncloud Code=120 "You are trying upload a file that does not exist" UserInfo={NSLocalizedDescription=You are trying upload a file that does not exist}

**Comment by enoch85** [comment] 2016-09-24 21:10
@frank9999 
> "You are trying upload a file that does not exist" UserInfo={NSLocalizedDescription=You are trying upload a file that does not exist}

Did you delete the file before the upload took place?

**Comment by frank9999** [comment] 2016-09-24 23:04
@enoch85

No I did not remove any files.

**Comment by rperezb** [comment] 2016-09-30 11:02
Found by @ggdiez the cause of the error

The image that the user tries to upload is not on the device, it's on iCloud and within the device there is only a thumbnail. 

Solution
1.- Try to get this photos from iCloud, it possible
2.- In case that it's not possible to get the images, show an error

Where do we show the error?

I'd suggest to show it within the uploads view as we do with other uploads errors

**Comment by enoch85** [comment] 2016-09-30 11:04
Another error, but would be nice to rename "File errror" to "File is missing when the user has removed the file before the upload takes place.

**Comment by rperezb** [comment] 2016-10-05 06:55
The aim of this issue is to update the error message so that it will be more explainatory
@enoch85 yes, we have to think about the error message itself but also about where to show it, perhaps not in the uploads view but before, once the user selects to upload the image from the gallery roll?

**Comment by enoch85** [comment] 2016-10-05 09:00
@rperezb Even better. The sooner the better. :)

**Comment by enoch85** [comment] 2016-10-19 20:46
I don't know if it's related but every time (I think it's every time) a file get's uploaded the server produces this error: 

```
Fatal	webdav	Exception: {"Message":"HTTP\/1.1 405 The resource you tried to create already exists","Exception":"Sabre\\DAV\\Exception\\MethodNotAllowed","Code":0,"Trace":"#0 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(588): Sabre\\DAV\\Server->createCollection('InstantUpload', Object(Sabre\\DAV\\MkCol))\n#1 [internal function]: Sabre\\DAV\\CorePlugin->httpMkcol(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#2 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#3 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(459): Sabre\\Event\\EventEmitter->emit('method:MKCOL', Array)\n#4 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#5 \/var\/www\/owncloud\/apps\/dav\/appinfo\/v1\/webdav.php(56): Sabre\\DAV\\Server->exec()\n#6 \/var\/www\/owncloud\/remote.php(164): require_once('\/var\/www\/ownclo...')\n#7 {main}","File":"\/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","Line":1121,"User":"kelly"}	2016-10-19T22:17:40+02:00
```

**Comment by jamimakus** [comment] 2016-10-25 16:56
I have also all kinds of error like this. Assuming thats caused by the fact full res images are on iCloud and not actually on the device. I switched iCloud Photo library off and lets see in a few days..

**Comment by rperezb** [comment] 2016-10-25 17:07
@jamimakus we plan to start working on it this week.
@ggdiez will take care.
Please, keep us updated with your test

**Comment by ggdiez** [comment] 2016-10-26 09:34
I have added an option to allow network access in the prepare files to upload process, doing that allow the system to download the image from iCloud if it's neccesary.

@jesmrec is ready to test here:

://github.com/owncloud/ios/tree/manage_photo_stream_items_from_icloud

**Comment by jesmrec** [comment] 2016-10-26 16:46
@ggdiez i have noticed the following issue: by uploading the shared videos from iCloud, the "loading" spinner remains forever:

![oct-26-2016 18-04-59](https://cloud.githubusercontent.com/assets/14894746/19734222/0ba0b172-9ba7-11e6-8722-54b64fbc5459.gif)

the spinner does not disappear until you kill the app. If you open it again, the uploads view is empty (the video was not queued)

The steps will be the following:

1. Connect a device to iCloud, in order to sync content from other devices connected to the same iCloud.
2. When videos are synced and visible in the device, try to upload them to ownCloud.

Current behaviour: The spinner does not disappear.
Expected: Video uploaded to ownCloud

Behaviour for photos is correct.

**Comment by ggdiez** [comment] 2016-10-27 07:59
I just added the same iCloud configuration for Videos. @jesmrec  check it again please.

**Comment by jesmrec** [comment] 2016-10-27 08:14
@ggdiez unfortunately it did not work :(

The problem keeps on happening

**Comment by ggdiez** [comment] 2016-10-28 13:01
@jesmrec unfortunately that option it seems that does not works with all the videos in iCloud. 

I have added a control to check if the video is properly exported in ownCloud. Doing that if the Videos does not work you get the usual "File Error" message in uploads view.

**Comment by rperezb** [comment] 2016-10-28 13:08
@ggdiez can we have a more specific error for this case?  at least: "error_file_does_not_exist" = "Source file not available on the device"
This is the one that we have updated in the case there is an error uploading a file from the cloud

**Comment by ggdiez** [comment] 2016-10-28 13:16
That solution is implemented in other branch :(.
When both branch are merged the message will be "Source file not available on the device"

**Comment by rperezb** [comment] 2016-10-28 13:20
you are right, for tracking purposes: https://github.com/owncloud/ios/tree/3.5.0.2_oem

**Comment by enoch85** [comment] 2016-10-28 14:16
> "Source file not available on the device"

Great! :+1:

**Comment by nasli** [comment] 2016-10-31 12:39
Due this branch 3.5.0.2_oem use 3.5.0 version and a lot of new translations has been done since that version, it is recommended to update the English language on this branch.

**Comment by nasli** [comment] 2016-10-31 13:10
I just updated the branch  https://github.com/owncloud/ios/tree/manage_photo_stream_items_from_icloud/Owncloud%20iOs%20Client with the new message error

**Comment by jesmrec** [comment] 2016-11-02 09:06
@ggdiez @nasli 

Right now the uploads view shows correctly the error when content can not be uploaded from iCloud (videos)

Behaviour for pics works correctly.

Approved.

**Comment by jesmrec** [comment] 2016-11-02 09:14
The error message is too long to be displayed completely

![screen shot 2016-11-02 at 10 10 37](https://cloud.githubusercontent.com/assets/14894746/19922900/0817794e-a0e5-11e6-83e3-fd8e45c1993d.png)

it should be shorten

CC @nasli, @ggdiez

**Comment by nasli** [comment] 2016-11-02 09:16
Updated to "Not available on the device"

**Comment by jesmrec** [comment] 2016-11-02 09:32
@nasli 

now the error message is completely displayed in iPad and iPhone

**Comment by nasli** [comment] 2016-11-02 09:38
@ggdiez could you generate the PR? Thanks!

**Comment by ggdiez** [comment] 2016-11-02 09:58
Done

https://github.com/owncloud/ios/pull/801

**Closed** 2016-11-03 11:32 UTC
Labels: approved by QA, Bug, sync::Instant uploads, sync::uploads

**Comment by enoch85** [comment] 2017-02-11 21:04
This still happens:

```
Sabre\DAV\Exception\MethodNotAllowed: HTTP/1.1 405 The resource you tried to create already exists
/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 590: Sabre\DAV\Server->createCollection('InstantUpload', Object(Sabre\DAV\MkCol))
[internal function] Sabre\DAV\CorePlugin->httpMkcol(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
/var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 479: Sabre\Event\EventEmitter->emit('method MKCOL', Array)
/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
/var/www/nextcloud/apps/dav/appinfo/v1/webdav.php - line 60: Sabre\DAV\Server->exec()
/var/www/nextcloud/remote.php - line 165: require_once('/var/www/nextcl...')
{main}
```

**Comment by rperezb** [comment] 2017-02-13 07:53
@enoch85 does this happen if you connect to an ownCloud server?

**Comment by enoch85** [comment] 2017-02-13 08:25
@rperezb True, didn't test that. This is Nextcloud actually. :hides:

**Comment by binarykitchen** [comment] 2017-03-11 19:09
this is bugging me too and also happens on latest iOS 3.5.3 client:

```
{"reqId":"ypbnyizToWMbe0DsP6vS","remoteAddr":"xxx","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 405 The resource you tried to create already exists\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\MethodNotAllowed\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(588): Sabre\\\\DAV\\\\Server->createCollection('InstantUpload', Object(Sabre\\\\DAV\\\\MkCol))\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpMkcol(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:MKCOL', Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(57): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/var\\\/www\\\/owncloud\\\/remote.php(164): require_once('\\\/var\\\/www\\\/ownclo...')\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php\",\"Line\":1121,\"User\":\"michael.heuberger\"}","level":4,"time":"2017-03-11T18:57:23+00:00","method":"MKCOL","url":"\/remote.php\/webdav\/InstantUpload\/","user":"xxx"}
```

is there a known workaround? can we somehow force to overwrite?

and it is funny, the remote instantupload folder is empty so why complain that it already exists? that's paradox ...

**Comment by michaelstingl** [comment] 2017-03-13 10:53
@binarykitchen Please open a new issue and provide all the required information. Thanks!

**Comment by nasli** [comment] 2017-03-13 10:59
@binarykitchen that is a different issue, you are not having file error in uploads, right?

What the server is complaining about is that the InstantUpload folder already exist, we are not checking on every uploads if it exists.
Please also check https://github.com/owncloud/ios/issues/373

**Comment by binarykitchen** [comment] 2017-03-14 00:20
sorry, cant do much - hard to reproduce

**Comment by enoch85** [comment] 2017-03-14 17:14
JFTR: Haven't seen this the past month.

**Comment by rperezb** [comment] 2017-03-14 17:14
Excellent news!

**Comment by enoch85** [comment] 2017-03-14 17:16
And btw, I like this app better than the Nextcloud app for iOS ;)

**Comment by davivel** [comment] 2017-03-14 17:20
@enoch85 , we also like you better than... we also like you better ;)
