### ISSUE TITLE
Error by choosing a folder by app

### ISSUE THREAD

**Issue by denisblum** [owncloud/ios#797] opened 2016-10-19 17:47 UTC
Please help us by providing the following info.
Steps to reproduce
1. Start APP Owncloud
2. Login successful
3. I can see all folder in the root directory
4. by choosing a folder i get the error message, that i have to check if the folder exists
Expected behaviour
Tell us what should happen
Actual behaviour
Tell us what happens instead
Mobile client configuration
Client OS (iOS, Android, ...): iOS
Server configuration
Operating system: 
Web server: apache
Database: mysql
PHP version: 5.6
ownCloud version (see ownCloud admin page): 9.1.0
Updated from an older ownCloud or fresh install: fresh
ownCloud log (data/owncloud.log):
Special configurations (external storage, external authentication, reverse proxy, server-side-encryption):

created
1h
last reply
31m1
reply

 
 
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Web server:**

**Database:**

**PHP version:**

### Client
**iOS version:**

**ownCloud app version:**

**Device model:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```
 
### Tell us what could be improved:

**Comment by denisblum** [comment] 2016-10-20 05:28
Additional info:
The error occures by using the owncloud app version 3.5.1 on iPhone.
Everything fine is by using the app by iPad or safari by desktop

**Comment by nasli** [comment] 2016-10-20 08:26
Thanks for your feedback @denisblum , we are checking it.
Duplicate of #770. Keep tracking there.

**Closed by nasli** 2016-10-20 08:26 UTC
