### ISSUE TITLE
Can browse directory structure, but no file access

### ISSUE THREAD

**Issue by evansnp** [owncloud/ios#355] opened 2015-05-01 08:03 UTC
The IOS  app connects to my server (8.0.2, running in Freenas Jail), but comes up with an error when trying to open files "It is not possible to connect to the server at this time".  If I try to access the same file via WEBDAV, all is good.

Note: I think that this has only happened since upgrading the server  from V7.

**Comment by georgehrke** [comment] 2015-05-01 14:22
I have the very same issue. Probably related to https://github.com/owncloud/ios/issues/214.
All http requests are redirected (301) to the same url with https.

**Comment by evansnp** [comment] 2015-05-11 15:38
Update: This has something to do with self signed certificates.
I upgraded to 8.0.3 today, checked the IOS app, and all was well.
re-instated my self signed certificates, and back to the original error message.

**Comment by georgehrke** [comment] 2015-05-11 15:40
self-signed cert in my environment as well.

**Comment by nasli** [comment] 2015-05-14 00:38
This could be related to a problem with the redirected servers. We are currently working on it and is under validation process. It will be fixed in next releases.
You can send us a test account to apps@owncloud.com in order to check if this problem is also fixed.
Thanks!

**Comment by nasli** [comment] 2015-05-22 12:37
Thanks @georgehrke for the test account, we could not reproduce it here. 
The issue could be related with this one #233

**Comment by nasli** [comment] 2015-05-22 12:41
@georgehrke check it this also https://forum.owncloud.org/viewtopic.php?f=24&t=9564&sid=a1bc96143f1a89f69b73b9dd9d7299f8&start=10#p29119

**Comment by rperezb** [comment] 2015-10-13 09:45
Close for inactivity, if needed, please reopen

**Closed by rperezb** 2015-10-13 09:45 UTC
