### ISSUE TITLE
Video upload from the asset upload picker is broken on Master

### ISSUE THREAD

**Issue by Jon-Schneider** [owncloud/ios#699] opened 2016-06-09 14:26 UTC
It looks like its due to a PrepareFilesToUpload not accounting for video assets as a type in the uploader method - all assets are assumed to be images. 

I will implement this fix after #698 is merged. Currently the Picker and refactored Instant Upload code paths in PrepareFilesToUpload are completely different - I would like to merge them, and fixing this would be a part of that. It would also be a good first step toward video instant upload.

Edit: Videos will "upload", but they're run through the image path and the uploaded video file is broken.

**Comment by Jon-Schneider** [comment] 2016-06-11 21:10
Track in PR #702

**Comment by jesmrec** [comment] 2016-06-13 11:04
@Jon-Schneider 

Do you mean that the videos were not being uploaded properly after the #698 was merged? i have tried to reproduce the problem in `master` branch but i was not be able. Can you give us a scenario to reproduce it in order to check that the problem is solved?  

For the moment, we do not expect the instant uploads for videos to be implemented.

**Comment by Jon-Schneider** [comment] 2016-06-13 11:14
@jesmrec I haven't had any issues reproducing from master. It would have been introduced when #679 was merged because there is not video upload code path.

Steps:

1) From files view in OwnCloud client, select the three dot button and then "Upload Photo/Video". Upload a video.

At this point you can check and see that the video file in OwnCloud is the wrong size compared the one you uploaded.

2) After it has finished uploading download it on your phone and try to play it. The video will fail to play.

**Closed** 2016-06-23 12:43 UTC
Labels: Bug
