### ISSUE TITLE
Pictures opens to black screen 

### ISSUE THREAD

**Issue by bisherbas** [owncloud/ios#457] opened 2015-08-29 16:08 UTC
See http://i.imgur.com/Jm161SX.jpg

Latest iOS on iPhone 5s. Https ownCloud 8.1.1

Sometimes it helps to quit the app and restart but this issue occurs constantly.

**Comment by javiergonzper** [comment] 2015-08-31 08:38
Hi @bisherbas 
Can you see any other document? For example a pdf.

**Comment by bisherbas** [comment] 2015-08-31 12:47
It is kind of hard to say because the issue occurs intermittently. But I have had cases where docx or pdf files did not open too. Instead of a black screen, those filed would be stuck at the initial screen with the associated icon in the middle.

**Comment by bisherbas** [comment] 2015-08-31 12:49
Here is my server info:

Server configuration
Ubuntu 14.04.3 64-bit
Apache2
MySQL
PHP 5.5.9
ownCloud 8.1.1
Fresh Install
Other apps: Notes, Calendar, Bookmarsks, Tasks

CONFIG.PHP:
<?php
$CONFIG = array (
'memcache.local' => '\OC\Memcache\APCu', 
'instanceid' => 'redacted',
'passwordsalt' => 'redacted',
'secret' => 'redacted',
'asset-pipeline.enabled' => true,
'trusted_domains' => 
array (
0 => 'domain.com',
),
'datadirectory' => '/var/www/owncloud/data',
'overwrite.cli.url' => 'http://domain.com/owncloud',
'dbtype' => 'mysql',
'version' => '8.1.1.3',
'dbname' => 'owncloud',
'dbhost' => 'localhost',
'dbtableprefix' => 'oc_',
'dbuser' => 'oc_redacted',
'dbpassword' => 'redacted',
'logtimezone' => 'UTC',
'installed' => true,
);

Are you using external storage, if yes which one:
NO

Are you using encryption: yes/no
NO

Are you using an external user-backend, if yes which one:
NO

Browser:
Any

Operating system:
Any

Web server error log
NONE

Insert your webserver log here
NONE

ownCloud log (data/owncloud.log)
NONE

Browser log
NONE

**Comment by javiergonzper** [comment] 2015-08-31 13:42
It is really strange. Looks like you have problems with the downloads.
Maybe the server are providing corrupted files or something like that. The point it is that here we can not reproduce it.
If you want you can send us a demo account of your server to apps@owncloud.com to try to check what it is happening with the files.

**Comment by rperezb** [comment] 2015-10-13 09:42
@bisherbas is your issue fixed within the latest version, 3.4.5?
IF not please, reopen

**Closed by rperezb** 2015-10-13 09:42 UTC
