### ISSUE TITLE
iOS Owncloud: upload background under "Photos" not working if Owncloud App left closed.

### ISSUE THREAD

**Issue by landrunner22002** [owncloud/ios#763] opened 2016-08-27 14:30 UTC
### Steps to reproduce

Settings>ownCloud>Location=Always
Settings>ownCloud>Photos=On
Settings>ownCloud>Background App Refresh=On
OwnCloud app itself>Settings>Instant Upload=On
OwnCloud not opened
Use Photos to select and upload using OwnCloud

### Expected behaviour
With OwnCloud closed and thank to "Background App Refresh" and "Instant Upload": the upload should works after selected images and exported via OwnCloud option under "Photos" iOs App.

### Actual behaviour
Nothing happen with upload background (waiting for 15mins to check)

Upload works only if I've opened OwnCloud App

### Server configuration
**Running on Raspberry Pi2
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 8.0 (jessie)
Release:	8.0
Codename:	jessie

**Web server: Apache/2.4.10 (Raspbian)

**Database: MySQL version: 5.5.50-0+deb8u1 - (Raspbian)

**PHP version: 4.2.12deb2+deb8u2

### Client
**iOS version: 9.3.4

**ownCloud app version: 3.5.0

**Device model: iPad Air 2 128Go

**Comment by Jon-Schneider** [comment] 2016-08-27 21:08
Did you force close the app or hit the home button?

**Comment by rperezb** [comment] 2016-08-29 07:25
@landrunner22002 did you change your position? Further details: https://github.com/owncloud/ios/issues/13#issuecomment-84890727

**Comment by landrunner22002** [comment] 2016-08-30 17:46
nothing works in background: you have to left Owncloud opened...

**Comment by enoch85** [comment] 2016-09-09 12:40
I can confirm this. Background uploads should work even if the app isn't started in the background.

**Comment by jesmrec** [comment] 2016-09-19 11:13
Checked in version 3.5.0 and works for me.

Background mode works if in the app settings are both `Instant Upload`and `Background Instant Upload` enabled. In that case, the pics you take while the app is in background mode will be uploaded when a significant location change happens. By disabling and enabling the device location services you can force this change if you really need it.

If `Background Instant Upload` is not enabled, the pics taken during the background mode will be uploaded when the app wakes up.

In the previous reported set up:

`Settings>ownCloud>Location=Always
Settings>ownCloud>Photos=On
Settings>ownCloud>Background App Refresh=On
OwnCloud app itself>Settings>Instant Upload=On
OwnCloud not opened
Use Photos to select and upload using OwnCloud`

does not appear the instant upload background mode as enabled.

If you share files from an external app (like Photos), the uploads will be performed always when the app wakes up, not in background.

**Comment by enoch85** [comment] 2016-09-19 12:33
The whole point of background uploads is that even if the app is closed, the uploads work anyway, just like android does it.

My use case is that I only want the instant upload function, I never use the app to browse for instance. That means that I need to manually start the app for uploads to be activated. That's not automatic, or instant, or in the background if you ask me.

**Comment by jesmrec** [comment] 2016-09-19 13:16
Background mode always means app closed or not in foreground. Now, as i have written previously, it works when the background mode is enabled for instant uploads and for manual uploads when they take more than 3 minutes, as expected. If not, please provide us steps to try to reproduce your problem as @landrunner22002 did.

**Comment by nasli** [comment] 2016-09-19 13:36
@enoch85  The only way to uploads automatically photos in background even when the app is not alive is to enable the new option added in app settings, "Background Instant uploads"
![screen shot 2016-09-19 at 15 21 21](https://cloud.githubusercontent.com/assets/6570505/18633554/2c961f9e-7e7d-11e6-955e-65f4fa609aeb.png)

With this option enabled, after a big changes in location are detected, the system provide us that event, and in this moment OC app check for new photos, and add them into a queue to upload. You do not need to open the app, they will upload automatically.

If following these steps, the new photos are not uploaded, please reopen with more descriptive steps, thanks.

**Closed by nasli** 2016-09-19 13:36 UTC
Labels: Bug, sev2-high
