### ISSUE TITLE
Certain folders no longer selectable as upload targets

### ISSUE THREAD

**Issue by workflowsguy** [owncloud/ios#788] opened 2016-09-29 13:42 UTC
Since the last two owncloud releases, I can no longer select some subfolders under the ownCloud directory as upload targets.

E.g. I want to upload an image into "Photos". In the folder selection dialog I can tap on "Photos" as much as I want, ownCloud client does not select it.

I suspect it has to do with a folder being empty. Because when I created a DUMMY.TXT file in the "Photos" directory on my Mac and had it sync back to iOS, then I was able to select it in the ownCloud client.

ownCloud Client for iOS 3.5.1
iOS 9.3.5

**Comment by nasli** [comment] 2016-10-14 12:05
@workflowsguy thanks for your feedback, 
We can not reproduce it, could you provide us more details?
Are you using iPad or iPhone?
Did you select to upload a photo from inside the app?
Version of your server? thanks

**Comment by workflowsguy** [comment] 2016-11-22 09:03
I experience the issue both on iPhone and iPad.

To reproduce:

1. I first select a group of fotos in Apple's Fotos app.
2. Then I tap the "Share" icon in the Fotos app, and in the share sheet select ownCloud as target.
3. In the ownCloud client, I tap on "Destination: ownCloud" at the bottom of the screen -> list of available folders synced through ownCloud shows up.
4. I tap on any of the folders shown (Documents, InstantUpload, Notes, Photos, Test), but none of them opens, regardless if they contain files or are empty. Sometimes I can see a window with short text and rotating cogwheel show up for a fraction of a second but it vanishes before I can read the text.
5. I put an empty Dummy.txt file in ownCloud's empty Photos folder on my Mac and then have ownCloud sync it back to the iPhone.
6. Then I repeat the steps 1 to 3 from above. Now when I tap on the Photos folder in the ownCloud client, it opens and is available as upload target (but all of the other directories still cannot be navigated into).

The ownCloud version of my server is ownCloud 8.2.3 (stable)
Thanks.

**Comment by workflowsguy** [comment] 2018-01-14 14:27
Hello,
several versions of iOS and ownCloud client later, this issue is still open.

**Comment by michaelstingl** [comment] 2018-01-14 21:15
@workflowsguy iOS 11 has a [screen recording feature](https://www.cnet.com/how-to/how-to-use-ios-11-built-in-screen-recording-feature/). Could you record it and send to apps@owncloud.com?

**Comment by workflowsguy** [comment] 2018-01-16 17:03
I have mailed two videos that hopefully show the issue.

**Comment by workflowsguy** [comment] 2018-01-29 06:32
The latest version (iOS 3.7.2 7a8df1e4) has made this issue even worse!

Now, even if I select a folder as target that I _can_ navigate into, the target location always stays at "ownCloud".

**Comment by rainboxx** [comment] 2018-02-28 07:37
For documentation purpose: I’m experiencing the same. The current beta, albeit mentioning a fix for this, doesn’t fix it.

**Comment by rainboxx** [comment] 2018-02-28 08:50
@nasli Good to know. The description seems to have been ambiguous 😉.

**Comment by patoperro** [comment] 2018-03-02 13:41
In Version 3.7.2 I can confirm that "Copy to OwnCloud" crashes the app. 
Using the option „OwnCloud“ I can change the folder I wish to upload to, but this has no effect on the result; the file is uploaded to the OwnCloud root directory.

**Comment by workflowsguy** [comment] 2018-03-06 14:52
Both the "Folder navigation" and the "Root folder" errors are still present in 3.7.3

**Comment by patoperro** [comment] 2018-03-06 17:06
can confirm 2 things:

1. workflowsguy is right about the "Folder navigation" and the "Root folder" errors are still present in 3.7.3
2. happily, the "Copy to OwnCloud" no longer crashes the app and works as intended

**Comment by jimmyott** [comment] 2018-06-03 20:46
Still present on 3.7.5 on iOS11.3.1
When can we expect a fix for this?

**Comment by michaelstingl** [comment] 2018-06-11 12:50
It seems the "Copy to ownCloud" feature is not available in all apps.

| Voice Memos | Photos | *.PDF in Safari |
|--- |---|---|
![img_3489](https://user-images.githubusercontent.com/214010/41231078-2b271ad2-6d82-11e8-8688-aa4b272e62e2.png) | ![img_3789](https://user-images.githubusercontent.com/214010/41231079-2b47938e-6d82-11e8-98f8-b46465da68a7.png) | ![img_3787](https://user-images.githubusercontent.com/214010/41231080-2b705b2a-6d82-11e8-8800-69e3db9ea748.png) |

**Comment by workflowsguy** [comment] 2018-06-12 15:00
@michaelstingl sorry, but I do not understand how this is relevant to issues reported.

**Comment by michaelstingl** [comment] 2018-06-12 18:41
@workflowsguy Previously I thought “Copy to ownCloud” can be used as a workaround in every case. After checking some more apps, I found “Copy to ownCloud” isn’t available in all apps.

**Comment by mochour** [comment] 2018-06-20 20:42
Hi,

you have closed my ticket #1035 due to this which is open more than 1 year. Is there any date when you are going to fix the issue? If this is not case, I'm going to open a ticket again.

I'm not satisfied with your approach to the problem.

Regards

**Comment by michaelstingl** [comment] 2018-06-21 10:16
@mochour I’m very sorry about the bad experience you have with the app. 

A new ticket won’t change anything. All relevant information is already in this issue. 

Let me tell you about our approach: In February, the ownCloud team started development of a new iOS app from scratch. Upload from 3rd party app is planned for the 1st release in the next few weeks. 

Here is the related issue in the repo of the new app: https://github.com/owncloud/ios-app/issues/76

**Comment by mochour** [comment] 2018-06-22 20:48
@michaelstingl  I ‘m basically satisfied with the app, but what bothers me is this approach when users are not informed about planned fixes and releases. You do a great job but keep in mind that [KCI](https://www.phaseware.com/phaseware-files-blog/phaseware-files-blog/bid/84232/good-customer-service-means-keeping-customers-informed) is the most important rule.  

Thanks

**Comment by michaelstingl** [comment] 2018-07-18 10:34
@javiergonzper what controlls if `Copy to ownCloud` is shown in an app or not?

**Comment by javiergonzper** [comment] 2018-07-18 11:01
@michaelstingl not sure why it is not appearing anymore I a seeing that also the `Copy to Dropbox` does no appear.
Anyway the `Copy to ownCloud` was the first way to send a file from other app to ownCloud that was developed for iOS6.
I can investigate it but is deprecated since Apple release the `Share In` extension.

> Still present on 3.7.5 on iOS11.3.1
> When can we expect a fix for this?

About the bug reported on this issue by @workflowsguy and @mochour (in a different issue) about the `Share In` extension. There are 2 bugs related on it:
- If you can navigate to a folder an select it the folder is not selected.
- You can not navigate if you are using a self signed certificate on the server side

Both bugs are fixed on the commit: https://github.com/owncloud/ios/commit/94559136e62303b0039e32c2252d207b3d233b66

Will be fixed on the next update 👍.

**Comment by ChrisEdS** [comment] 2018-07-30 11:50
@javiergonzper @jesmrec Just tested the fix works really good. In my opinion, we can improve the `Share In` extension in two points:

1. The `Cancel` and `Upload to` button is greyed out. This usually means that something cannot be used. This is not the case here.
2. Replacing the text "ownCloud" and use the icon instead. In other `Sheets` we use the icon - we should consistently stick to one variant.

![img_0001](https://user-images.githubusercontent.com/33026403/43395715-5468940e-93ff-11e8-9907-b1e5bbb06c23.jpg)

**Comment by jesmrec** [comment] 2018-07-30 12:57
only to take in account: the use of the icon will carry branding changes. isn't it @javiergonzper ?

**Comment by javiergonzper** [comment] 2018-07-31 06:29
@ChrisEdS you are right about the colours. Are not set correctly, I will change it on this branch.
About the icon, @jesmrec it is not needed branding changes because it is change the behavior of that navigation bar to have the same behavior that we have on the main file list.

<img width="255" alt="screen shot 2018-07-31 at 08 28 14" src="https://user-images.githubusercontent.com/1815050/43441611-b576722e-949b-11e8-9c80-6709e099b3ec.png">

**Comment by jesmrec** [comment] 2018-08-14 10:53
Stuff fixed. It will be available in next release.

**Closed by jesmrec** 2018-08-14 10:53 UTC
Labels: Bug
