### ISSUE TITLE
IOS 8.2/ownCloud 3.4.0: Open With does not show other Apps

### ISSUE THREAD

**Issue by Cagorso** [owncloud/ios#332] opened 2015-03-28 19:01 UTC
When you select a  file and choose "Open With ..." it does only show the following Applications:
Message
Mail
Evernote
I've tried with any kind of file: doc, mp3, odt, txt, jpg but nothing. I have a lots of apps that can handle these type of files but none of them are shown when I tap 'Open with..'

**Comment by tflidd** [comment] 2015-03-29 11:57
Duplicate of https://github.com/owncloud/ios/issues/331 and https://github.com/owncloud/ios/issues/323. In https://github.com/owncloud/ios/issues/323, a fix is announced to be published soon.

**Comment by rperezb** [comment] 2015-03-30 16:14
Thanks! lets follow its status on #323

**Closed by rperezb** 2015-03-30 16:14 UTC
