### ISSUE TITLE
ISO 8.2/ownCloud 3.4.0 Bug: Open With does not show other Apps

### ISSUE THREAD

**Issue by nona00** [owncloud/ios#331] opened 2015-03-28 17:48 UTC
When you select an audio file (wav or mp3) and choose "Open With ..." it does only show the following Applications:
News
Mail

![Uploading Photo-2015-03-28-18-44-55_0247.PNG . . .]()

It seems not to be possible to load a audio file into an other app (e.g. Audio editor or VLC)

**Comment by tflidd** [comment] 2015-03-29 11:57
Probably duplicate of https://github.com/owncloud/ios/issues/323. Fix is on the way.

**Comment by rperezb** [comment] 2015-03-30 16:14
Thanks! lets follow its status on #323

**Closed by rperezb** 2015-03-30 16:14 UTC
