### ISSUE TITLE
Storage Provider App Extension for iOS 8

### ISSUE THREAD

**Issue by nicokaiser** [owncloud/ios#193] opened 2014-06-03 19:51 UTC
iOS 8 allowes apps to supply extensions for other apps outside the sandbox.

> **Storage Provider**
> You can now provide a document storage location that can be accessed by other apps. Apps that use a document picker view controller can open files managed by the storage provider or move files into the storage provider.

https://developer.apple.com/ios8/

It would be amazing if ownCloud could provide a Storage Provider extension which allows access to any document stored in an ownCloud instance from any app (that supports iCloud Document Storage).

**Comment by rperezb** [comment] 2015-01-08 10:11
work in progress: 
https://github.com/owncloud/ios/tree/download_on_document_provider
https://github.com/owncloud/ios/tree/upload_on_document_provider

**Comment by andusvan** [comment] 2015-02-18 20:28
Hello!

How's the progress on this?
I'm asking, because the two given links do not work anymore...

And I want to know, if you plan to extend the "system Share sheet" of iOS, too?

Regards
 Sven

**Comment by nasli** [comment] 2015-03-12 17:09
The document provider feature is ready and will be within the new version 3.4.0.

The share sheet feature its currently under development process and will be included in future versions. :)

**Comment by andusvan** [comment] 2015-03-12 19:23
Thank you for the information!
I can't await the new version ;-)

**Comment by pouipsch** [comment] 2015-03-22 12:48
Hi

I saw the update arrive a couple of days ago. I can now enable ownCloud as a Storage Provider but ownCloud never actually appears as a source when I go to add a file from other apps. I tried on a few different iOS devices all running iOS 8.2. Anyone else seeing the same thing?

**Comment by javiergonzper** [comment] 2015-03-23 10:15
HI @pouipsch which apps are you using? Document Provider only works on apps that support Document Provider. For example Word or Documents

**Comment by andusvan** [comment] 2015-03-23 10:57
Hello!
It would be nice to have a list (of common) Apps, which support the Document Provider. Which Apps did the developers use to test it?
Does the coming "share sheet feature" also only work with certain Apps or is this independent?

**Comment by tflidd** [comment] 2015-03-23 11:00
The pages-app seems to work for me but a lot of others don't: https://github.com/owncloud/ios/issues/323

**Comment by javiergonzper** [comment] 2015-03-23 13:31
@andusvan We used mainly "Documents"
https://itunes.apple.com/es/app/documents-5-lector-rapido/id364901807?mt=8
Probably was the first that support Document Provider. Since a few weeks Word also support it but you can not edit a document if you do not pay.

@tflidd that it is a different issue not related with the Document Provider. As you can see @ggdiez was working to fix it :+1:

**Comment by pouipsch** [comment] 2015-03-24 00:04
Hi Javier, thanks for your response.

I had understood from the release notes "access your files from other iOS apps" that for example if I wanted to add a file to Google Drive on iOS, files in ownCloud would be selectable as a source. Apologies if I've misunderstood the functionality.

Cheers!

**Comment by javiergonzper** [comment] 2015-03-24 09:43
Do not worry @pouipsch :wink: . There are many things very similar (open with, open in, share in, Document Provider...) that looks like the same but at the end are completely different.

**Comment by mtoivo** [comment] 2015-03-30 09:40
Tried to open files from Drafts -application. I can switch owncloud on as a storage provider (inside Drafts app), but the switch doesn't turn into green but blue instead, and ownloud never appears in the list of possible locations. Only iCloud is visible. Any idea what could be wrong?

**Comment by frankesario** [comment] 2015-04-07 09:54
I can confirm that it is not possible to use owncloud 3.4.1 as a storage provider in most cases. A good example is GoodReader4 where you have the possibillity to open the document directly or open a copy of the document with the file picker. "Import (copy) from iCloud drive" doesn't work with owncloud as document provider whereas "Open file from iCloud drive" works. Owncloud is simply not selectable. Other apps providing an interface for the file picker like the Synology file browser operate as expected in both cases.
Here some more apps in which I can't use owncloud as provider: VLC, Workflow, Synology apps

**Comment by javiergonzper** [comment] 2015-04-07 10:21
Hi @frankesario 
It is strange. It should works but you are right on those apps the ownCloud Document Provider is not accessible... we will check it.

Thanks for report

**Comment by javiergonzper** [comment] 2015-04-07 11:04
The problem is that there are those ways to use the Document Provider:

     <string>UIDocumentPickerModeImport</string>
     <string>UIDocumentPickerModeOpen</string>
     <string>UIDocumentPickerModeExportToService</string>
     <string>UIDocumentPickerModeMoveToService</string>

We only have implemented the "UIDocumentPickerModeOpen". Looks like the Synology apps and the VLC use the "UIDocumentPickerModeImport" (duplication of the file). We did not implement that way because you can use the "Open In" option of ownCloud to do exactly the same (a duplication of the file).

I tested it and looks like the "UIDocumentPickerModeImport" works without problem with the current implementation so maybe we can add it to be tested but it is decision of @MTRichards to be prioritize.

**Comment by frankesario** [comment] 2015-04-08 09:58
@javiergonzper 
Great that you responded that quickly and even checked the owncloud app code.
Take in mind that the usability is generally better if you don't have to leave the app you are using. Also in Workflow you need this functionallity cause it is a workflow you build. Neither you can export things to it nor you can switch to another app to use "open In" here. This shows that there are cases where the "UIDocumentPickerModeImport" mode is essential.

**Comment by mtoivo** [comment] 2015-04-08 10:09
@javiergonzper I agree that instead of copying the file around in each app's sandboxes, the main prority should be making this UIDocumentPickerModeOpen work flawlessly first. Is it possible to offer all the methods, or do you have to pick one?

**Comment by cycloon** [comment] 2015-04-15 09:50
Nice to see this progress. Thanks to all who worked on it.

As we can now open files, is it possible to save them back to owncloud? Or even have them automatically saved back for example when edited in Pages or Numbers?

**Comment by javiergonzper** [comment] 2015-04-15 10:17
@frankesario yes totally true. I think that we will add the Import mode on the next release. It was not before because when we started to work with the Document Provider we did not know how the other apps will implement it.

@mtoivo i do not know if we will add all the methods. Maybe the export it is not necessary... we have to think about it.

@cycloon with the UIDocumentPickerModeOpen once the "other app" finish the edition the file is sent automatically to the Document Provider and upload to ownCloud :+1:. Pages or Numbers should works but I did not try it. We used https://itunes.apple.com/es/app/documents-5-lector-rapido/id364901807?mt=8 to develop the Document Provider and it works as it should.

**Comment by lkrms** [comment] 2015-05-11 23:13
Thanks for your work on this extension.

I'm finding one small issue with it, though--if I edit an ownCloud document in, say, Pages, everything works fine, but I can't re-open the same document until I've opened the ownCloud app, allowed it to finish syncing the change back up to ownCloud, then re-opened Pages. I *assume* this is an ownCloud bug. Removing the ownCloud app PIN and enabling Instant Upload doesn't make a difference.

**Comment by mathiasfriman** [comment] 2015-05-12 09:19
Just want to reference my issue here as well: #361

**Comment by nasli** [comment] 2015-07-15 09:00
The next release 3.4.4 will support all types of document provider modes.
 @andusvan, also will support the share in extension.
 It will be able to share with all the apps that have implemented the document provider feature. 

@lkrms, there is no bug, this is the current behavior, when you edit a file, that file is pending to be uploaded and you need to open the app to uploaded and have the last version.
The Instant upload options is to enable instant uploads of all new photos we take with the device since it has been activated. Sorry for the confusion, in future version we plan to inform better how this feature works.

@mathiasfriman thanks for your comment.

**Closed by nasli** 2015-07-15 09:00 UTC
Labels: Enhancement

**Comment by andusvan** [comment] 2015-07-15 09:34
Thank you very much!
That's what I hoped for...
