### ISSUE TITLE
multiple Photo upload selection and other feature requests

### ISSUE THREAD

**Issue by hutchwilco** [owncloud/ios#271] opened 2015-01-16 00:17 UTC
Hi,
A few thoughts that would increase the utility of this app (for me at least)
1. Easy way to "select all" photos in an album for upload, or select a range of photos viewable on the screen (the point being without having to tap each and every photo)
2. Auto upload photos (say when connected to power and wifi) - similar to dropbox and google drive image upload functionality)
3. integration with iOS8 extensions so that "Open in..." and other Share functions are available for OwnCloud.
4. Ability to use "Workflow" app to create scripts for getting files into OwnCloud (ties in with #3 above)
5. Ability to manage failed uploads en-masse - currently you have to work through each individual upload error/issue. Should be able to "apply action to all".
#1 is probably the most key feature I'm missing though.

Thanks!

**Comment by javiergonzper** [comment] 2015-01-16 08:19
Hi @hutchwilco thanks for share those ideas with us.

1. That it is dangerous... if the user select an album with thousands of photos probably will be stuck during a long time until we move all the photos to the upload process.
2. We are working on instant uploads to upload the new photos but in the future we have to add conditions as you want (charging, only wifi...).
3. Yes we are working now on the Document Provider but also we have to work on the new Share interface.
4. What do you mean? After an update you lose the files that are on your device? We are especially careful to that does not happen.
5. Thats would be awesome. We do that if you change your credentials but I think that we do not do that on other cases like when you try to upload several files to a folder that does not exist.

About the #1 we have to check the resolution but I think that we do not have any problem about reduce the resolution of the picture. The format yes... haver to check why it change to PNG because the iPhone take the pictures on JPG.

Thanks
Javi

**Comment by hutchwilco** [comment] 2015-01-16 23:10
Hi Javi, thanks for reading my comments.
1. I understand that danger, but perhaps the app can check and apply a limit( say max is 100 photos). My point is not the maximum, but the method of selection. Just as in Windows or Mac, you can select a range of consecutive files using Shift key. With current owncloud app I can select many many photos but it would just take me a long tedious time as I need to tap on every single photo I wish to upload.
2. Great! I like Plex app execution of this feature- a good model! Allowing many controls to the user to exclude mobile data, require charger connected etc...
4. Workflow app allows me to build a script on my iPhone to complete a task, such as batch resize photos and upload to, say Dropbox. Would be useful to have owncloud functions too. But this is probably dreaming, or a question for the developers of Workflow app.
5. I had many failed due to "existing file name" (which was not true!- owncloud was mistaken somehow) but I could only clear the errors one by one.

Thanks again, your app has made good advances in functionality.

**Comment by javiergonzper** [comment] 2015-01-19 07:29
4. Ohhh I see. But it is Workflow how have to implement that options. We release a SDK to allow other app access easy to ownCloud server.
5. Ouch. That it is a problem, wich version are you using on your server? Can you reproduce that bug?
Anyway you are right, we could detect if the queue of the uploads have any file with conflict error and show to the user the option to do the same. 

You are welcome. It is great read tje opinion of the users :wink:

**Comment by mbardelmeijer** [comment] 2015-11-11 09:06
Would also like the first option (select all the pictures for a initial upload). Any change this will be implemented soon?

**Comment by javiergonzper** [comment] 2015-11-11 09:14
@mbardelmeijer  I do not think so. Right now we are focus on "Download folder", "Favourite folder", "Share"... we have a very long roadmap...

**Comment by rgbeard** [comment] 2015-11-18 19:57
I'm new to Owncloud, and getting an initial sync done of photos from my iPhone.  

I've run into trying to upload files twice (as there's not a really good way to know what's uploaded, and what's not) and it creates "conflict errors".  I don't see a choice to say "Skip".  Only overwrite or rename.  I would see great utility in a "skip" feature.

**Comment by javiergonzper** [comment] 2015-11-19 07:27
Hello @rgbeard if you swipe on the upload from right to left you can delete the upload

**Comment by rgbeard** [comment] 2015-11-22 16:00
@javiergonzper - when the status is conflict error, I do not believe the swipe works.

If I choose rename, enter new name, I can hit the circle-X and kill it.  I'll test to make sure my assessment is accurate.

**Comment by nasli** [comment] 2015-11-23 16:35
@rgbeard, what @javiergonzper mean was the following swipe button
![captura de pantalla 2015-11-23 a las 17 14 22](https://cloud.githubusercontent.com/assets/6570505/11342068/b7deff0e-9205-11e5-9614-f2d673b41ae4.png)
it is possible to delete the upload with conflict.
The cicle-x button is to cancel the upload while is uploading, but after a conflict you have to use "delete" button

**Comment by nasli** [comment] 2017-03-08 11:52
Since all the points requested here has been already fixed or redefined in more specific issues I will close this one.

For the pending request to upload all your photos at once, please keep tracking here #846

**Closed by nasli** 2017-03-08 11:52 UTC
