### ISSUE TITLE
Public-link creation not possible when "Enforce password protection" is set

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ios#855] opened 2017-03-09 20:51 UTC
### Steps to reproduce

![admin_-_owncloud](https://cloud.githubusercontent.com/assets/214010/23769899/3cef341e-0511-11e7-81df-da91cd948c86.png)

### Expected behaviour

ownCloud iOS app should detect this setting and should show input to set password.

### Actual behaviour

![public-share-password](https://cloud.githubusercontent.com/assets/214010/23769950/6df1e12e-0511-11e7-873e-21f28d624a94.gif)

### Server configuration
**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
PHP 7

### Client
**iOS version:**
10.3 (beta)

**ownCloud app version:**
3.5.3

**Device model:**
iPhone 7 Plus (mirrored with Reflector app)

### Tell us what could be improved:

Normally the iOS system share menu comes up immediately when clicking the switch. I would be better to trigger this after klicking the "Get Share link" button IF "Enforce password protection" or "Enforce expiration date" has been set.

**Comment by michaelstingl** [comment] 2017-03-09 20:54
@jesmrec please also check with settings from "Share Link Password Policy" app in ownCloud Enterprise:
https://doc.owncloud.com/server/9.1/admin_manual/configuration_files/file_sharing_configuration.html#password-policy-label

**Comment by nasli** [comment] 2017-03-10 10:06
@michaelstingl witch server version ?

**Comment by michaelstingl** [comment] 2017-03-10 10:29
@nasli I tested with 9.1.4 CE

**Comment by jesmrec** [comment] 2017-03-10 14:32
Maybe the capabilities are not updated in the moment you enable the "Share link". Could you check these two cases? (after enabling the server capability):

- Switch to another account in the device and return to the first one. Then, check if the pw is asked when the share link is enabled
- Close the app and open it again. Check if the pw is asked when the share link is enabled

In those cases, the server capabilities are refreshed on the device. If not, the app does not know that the "Enforce password" is enabled and the server does not allow to create it.

I will also check with "Share Link Password Policy". I will post here results.

@michaelstingl

**Comment by michaelstingl** [comment] 2017-03-10 14:48
> Switch to another account in the device and return to the first one. Then, check if the pw is asked when the share link is enabled

👍  After switching accounts it worked.

> Close the app and open it again. Check if the pw is asked when the share link is enabled

Closing the app isn't enough, but force-quit helped. 👍

**Comment by jesmrec** [comment] 2017-03-10 18:38
right, is not only needed to minimize, also is required closing the app to force the capabilities updating. This behaviour is the expected one.

**Comment by nasli** [comment] 2017-05-02 12:24
As @jesmrec said , it is not a bug, you need to kill the app or switch the user.

**Closed by nasli** 2017-05-02 12:24 UTC
Labels: Bug, sharing
